// Code generated by stefc. DO NOT EDIT.
use rand::Rng;
use stef_core::schema::WireSchema;

use crate::*;
use crate::common::{Allocators, MutateRandomLimiter};

#[derive(Debug, Clone, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize)]
pub struct ExpHistogramBuckets {
    pub offset:i64,
    pub bucketCounts:Uint64Array,
    frozen: bool,
}

impl Default for ExpHistogramBuckets {
    fn default() -> Self {
        let mut s = Self {
            offset:Default::default(),
            bucketCounts:Default::default(),
            frozen: false,
        };
        s.init();
        s
    }
}

impl ExpHistogramBuckets {
    pub fn Init(&mut self) {
        self.init();
    }

    pub fn init(&mut self) {
        self.offset = Default::default();
        self.bucketCounts = Default::default();
        self.frozen = false;
    }

    pub fn new_() -> Self {
        Self::default()
    }

    pub fn NewExpHistogramBuckets() -> Self {
        Self::default()
    }

    pub fn init_alloc(&mut self, _allocators: &mut Allocators) {
        self.init();
    }

    pub fn reset(&mut self) {
        self.init();
    }

    pub fn freeze(&mut self) {
        self.frozen = true;
    }

    pub fn Freeze(&mut self) {
        self.freeze();
    }

    pub fn is_frozen(&self) -> bool {
        self.frozen
    }

    pub fn fix_parent(&mut self) {}
    pub fn Offset(&self) -> i64 {
        self.offset.clone()
    }

    pub fn SetOffset(&mut self, v: i64) {
        self.offset = v;
    }

    
    pub fn BucketCounts(&self) -> Uint64Array {
        self.bucketCounts.clone()
    }

    pub fn SetBucketCounts(&mut self, v: Uint64Array) {
        self.bucketCounts = v;
    }

    

    pub fn set_modified_recursively(&mut self) {}

    pub fn set_unmodified_recursively(&mut self) {}

    pub fn compute_diff(&self, val: &ExpHistogramBuckets) -> bool {
        self != val
    }

    pub fn can_be_shared(&self) -> bool {
        self.frozen
    }

    pub fn clone_shared(&self, _allocators: &mut Allocators) -> Self {
        self.clone()
    }

    pub fn Clone(&self, _allocators: &mut Allocators) -> Self {
        self.clone()
    }

    pub fn byte_size(&self) -> usize {
        core::mem::size_of::<Self>()
    }

    pub fn copy_from(&mut self, src: &ExpHistogramBuckets) {
        *self = src.clone();
    }

    pub fn CopyFrom(&mut self, src: &ExpHistogramBuckets) {
        self.copy_from(src);
    }

    pub fn mutate_random<R: Rng + ?Sized>(&mut self, _random: &mut R, _limiter: &mut MutateRandomLimiter) {
    }

    pub fn is_equal(&self, right: &ExpHistogramBuckets) -> bool {
        self == right
    }
}

pub fn copy_ExpHistogramBuckets(dst: &mut ExpHistogramBuckets, src: &ExpHistogramBuckets) {
    dst.copy_from(src);
}

pub fn copy_to_new_ExpHistogramBuckets(dst: &mut ExpHistogramBuckets, src: &ExpHistogramBuckets, _allocators: &mut Allocators) {
    dst.copy_from(src);
}

pub fn eq_ExpHistogramBuckets(left: &ExpHistogramBuckets, right: &ExpHistogramBuckets) -> bool {
    left == right
}

pub fn cmp_ExpHistogramBuckets(left: &ExpHistogramBuckets, right: &ExpHistogramBuckets) -> i8 {
    if left == right {
        0
    } else if left < right {
        -1
    } else {
        1
    }
}


