// Code generated by stefc. DO NOT EDIT.
use rand::Rng;
use stef_core::schema::WireSchema;

use crate::*;
use crate::common::{Allocators, MutateRandomLimiter};

#[derive(Debug, Clone, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize)]
pub struct Point {
    pub startTimestamp:u64,
    pub timestamp:u64,
    pub value:PointValue,
    pub exemplars:ExemplarArray,
    frozen: bool,
}

impl Default for Point {
    fn default() -> Self {
        let mut s = Self {
            startTimestamp:Default::default(),
            timestamp:Default::default(),
            value:Default::default(),
            exemplars:Default::default(),
            frozen: false,
        };
        s.init();
        s
    }
}

impl Point {
    pub fn Init(&mut self) {
        self.init();
    }

    pub fn init(&mut self) {
        self.startTimestamp = Default::default();
        self.timestamp = Default::default();
        self.value = Default::default();
        self.exemplars = Default::default();
        self.frozen = false;
    }

    pub fn new_() -> Self {
        Self::default()
    }

    pub fn NewPoint() -> Self {
        Self::default()
    }

    pub fn init_alloc(&mut self, _allocators: &mut Allocators) {
        self.init();
    }

    pub fn reset(&mut self) {
        self.init();
    }

    pub fn freeze(&mut self) {
        self.frozen = true;
    }

    pub fn Freeze(&mut self) {
        self.freeze();
    }

    pub fn is_frozen(&self) -> bool {
        self.frozen
    }

    pub fn fix_parent(&mut self) {}
    pub fn StartTimestamp(&self) -> u64 {
        self.startTimestamp.clone()
    }

    pub fn SetStartTimestamp(&mut self, v: u64) {
        self.startTimestamp = v;
    }

    
    pub fn Timestamp(&self) -> u64 {
        self.timestamp.clone()
    }

    pub fn SetTimestamp(&mut self, v: u64) {
        self.timestamp = v;
    }

    
    pub fn Value(&self) -> PointValue {
        self.value.clone()
    }

    pub fn SetValue(&mut self, v: PointValue) {
        self.value = v;
    }

    
    pub fn Exemplars(&self) -> ExemplarArray {
        self.exemplars.clone()
    }

    pub fn SetExemplars(&mut self, v: ExemplarArray) {
        self.exemplars = v;
    }

    

    pub fn set_modified_recursively(&mut self) {}

    pub fn set_unmodified_recursively(&mut self) {}

    pub fn compute_diff(&self, val: &Point) -> bool {
        self != val
    }

    pub fn can_be_shared(&self) -> bool {
        self.frozen
    }

    pub fn clone_shared(&self, _allocators: &mut Allocators) -> Self {
        self.clone()
    }

    pub fn Clone(&self, _allocators: &mut Allocators) -> Self {
        self.clone()
    }

    pub fn byte_size(&self) -> usize {
        core::mem::size_of::<Self>()
    }

    pub fn copy_from(&mut self, src: &Point) {
        *self = src.clone();
    }

    pub fn CopyFrom(&mut self, src: &Point) {
        self.copy_from(src);
    }

    pub fn mutate_random<R: Rng + ?Sized>(&mut self, _random: &mut R, _limiter: &mut MutateRandomLimiter) {
    }

    pub fn is_equal(&self, right: &Point) -> bool {
        self == right
    }
}

pub fn copy_Point(dst: &mut Point, src: &Point) {
    dst.copy_from(src);
}

pub fn copy_to_new_Point(dst: &mut Point, src: &Point, _allocators: &mut Allocators) {
    dst.copy_from(src);
}

pub fn eq_Point(left: &Point, right: &Point) -> bool {
    left == right
}

pub fn cmp_Point(left: &Point, right: &Point) -> i8 {
    if left == right {
        0
    } else if left < right {
        -1
    } else {
        1
    }
}


