// Code generated by stefc. DO NOT EDIT.
use rand::Rng;

use crate::*;
use crate::common::{Allocators, MutateRandomLimiter};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Default, serde::Serialize, serde::Deserialize)]
pub enum PointValueType {
    #[default]
    None,
    Int64,
    Float64,
    Histogram,
    ExpHistogram,
    Summary,
}

#[derive(Debug, Clone, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize)]
pub struct PointValue {
    pub typ: PointValueType,
    pub int64:i64,
    pub float64:f64,
    pub histogram:HistogramValue,
    pub expHistogram:ExpHistogramValue,
    pub summary:SummaryValue,
    frozen: bool,
}

impl Default for PointValue {
    fn default() -> Self {
        let mut s = Self {
            typ: PointValueType::None,
            int64:Default::default(),
            float64:Default::default(),
            histogram:Default::default(),
            expHistogram:Default::default(),
            summary:Default::default(),
            frozen: false,
        };
        s.init();
        s
    }
}

impl PointValue {
    pub fn Init(&mut self) {
        self.init();
    }

    pub fn init(&mut self) {
        self.typ = PointValueType::None;
        self.frozen = false;
    }

    pub fn init_alloc(&mut self, _allocators: &mut Allocators) {
        self.init();
    }

    pub fn reset(&mut self) {
        self.typ = PointValueType::None;
    }

    pub fn freeze(&mut self) {
        self.frozen = true;
    }

    pub fn fix_parent(&mut self) {}

    pub fn type_(&self) -> PointValueType {
        self.typ
    }

    pub fn Type(&self) -> PointValueType {
        self.type_()
    }

    pub fn reset_contained(&mut self) {}

    pub fn set_type(&mut self, typ: PointValueType) {
        if self.typ != typ {
            self.typ = typ;
            self.reset_contained();
            self.mark_parent_modified();
        }
    }

    pub fn SetType(&mut self, typ: PointValueType) {
        self.set_type(typ);
    }
    pub fn Int64(&self) -> i64 {
        self.int64.clone()
    }

    pub fn SetInt64(&mut self, v: i64) {
        self.typ = PointValueType::Int64;
        self.int64 = v;
    }
    pub fn Float64(&self) -> f64 {
        self.float64.clone()
    }

    pub fn SetFloat64(&mut self, v: f64) {
        self.typ = PointValueType::Float64;
        self.float64 = v;
    }
    pub fn Histogram(&self) -> HistogramValue {
        self.histogram.clone()
    }

    pub fn SetHistogram(&mut self, v: HistogramValue) {
        self.typ = PointValueType::Histogram;
        self.histogram = v;
    }
    pub fn ExpHistogram(&self) -> ExpHistogramValue {
        self.expHistogram.clone()
    }

    pub fn SetExpHistogram(&mut self, v: ExpHistogramValue) {
        self.typ = PointValueType::ExpHistogram;
        self.expHistogram = v;
    }
    pub fn Summary(&self) -> SummaryValue {
        self.summary.clone()
    }

    pub fn SetSummary(&mut self, v: SummaryValue) {
        self.typ = PointValueType::Summary;
        self.summary = v;
    }

    pub fn can_be_shared(&self) -> bool {
        self.frozen
    }

    pub fn clone_shared(&self, _allocators: &mut Allocators) -> Self {
        self.clone()
    }

    pub fn Clone(&self, _allocators: &mut Allocators) -> Self {
        self.clone()
    }

    pub fn byte_size(&self) -> usize {
        core::mem::size_of::<Self>()
    }

    pub fn copy_from(&mut self, src: &PointValue) {
        *self = src.clone();
    }

    pub fn CopyFrom(&mut self, src: &PointValue) {
        self.copy_from(src);
    }

    pub fn mark_parent_modified(&mut self) {}

    pub fn set_modified_recursively(&mut self) {}

    pub fn set_unmodified_recursively(&mut self) {}

    pub fn compute_diff(&self, val: &PointValue) -> bool {
        self != val
    }

    pub fn is_equal(&self, val: &PointValue) -> bool {
        self == val
    }

    pub fn mutate_random<R: Rng + ?Sized>(&mut self, _random: &mut R, _limiter: &mut MutateRandomLimiter) {
    }
}

pub fn copy_PointValue(dst: &mut PointValue, src: &PointValue) {
    dst.copy_from(src);
}

pub fn copy_to_new_PointValue(dst: &mut PointValue, src: &PointValue, _allocators: &mut Allocators) {
    dst.copy_from(src);
}

pub fn eq_PointValue(left: &PointValue, right: &PointValue) -> bool {
    left == right
}

pub fn cmp_PointValue(left: &PointValue, right: &PointValue) -> i8 {
    if left == right {
        0
    } else if left < right {
        -1
    } else {
        1
    }
}
