// Code generated by stefc. DO NOT EDIT.
use stef_core::{SizeLimiter, WriterOptions};

use crate::*;
use crate::common::StructFieldCounts;

#[derive(Debug, Default)]
pub struct WriterState {
    pub limiter: SizeLimiter,
    pub struct_field_counts: StructFieldCounts,

    // Dictionaries
    pub AnyValueString: Vec<String>,
    pub AttributeKey: Vec<String>,
    pub Metric: Vec<Metric>,
    pub MetricDescription: Vec<String>,
    pub MetricName: Vec<String>,
    pub MetricUnit: Vec<String>,
    pub Resource: Vec<Resource>,
    pub SchemaURL: Vec<String>,
    pub Scope: Vec<Scope>,
    pub ScopeName: Vec<String>,
    pub ScopeVersion: Vec<String>,
    pub SpanEventName: Vec<String>,
    pub SpanName: Vec<String>,
    
}

impl WriterState {
    pub fn init(&mut self, opts: &WriterOptions) {
        self.limiter.init(opts);
        self.struct_field_counts.init(opts.schema.clone());

        self.AnyValueString.clear();
        self.AttributeKey.clear();
        self.Metric.clear();
        self.MetricDescription.clear();
        self.MetricName.clear();
        self.MetricUnit.clear();
        self.Resource.clear();
        self.SchemaURL.clear();
        self.Scope.clear();
        self.ScopeName.clear();
        self.ScopeVersion.clear();
        self.SpanEventName.clear();
        self.SpanName.clear();
        
    }

    pub fn reset_dicts(&mut self) {
        self.limiter.reset_dict();
        self.AnyValueString.clear();
        self.AttributeKey.clear();
        self.Metric.clear();
        self.MetricDescription.clear();
        self.MetricName.clear();
        self.MetricUnit.clear();
        self.Resource.clear();
        self.SchemaURL.clear();
        self.Scope.clear();
        self.ScopeName.clear();
        self.ScopeVersion.clear();
        self.SpanEventName.clear();
        self.SpanName.clear();
        
    }
}
