// Code generated by stefgen. DO NOT EDIT.
package oteltef

import (
	"fmt"
	"strings"
	"unsafe"

	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/encoders"
)

var _ = strings.Compare
var _ = encoders.StringEncoder{}

type HistogramValue struct {
	count        int64
	sum          float64
	min          float64
	max          float64
	bucketCounts Int64Array

	// modifiedFields keeps track of which fields are modified.
	modifiedFields modifiedFields

	// Field presence bits.
	// Fields which are present have the corresponding bit set, see fieldPresentHistogramValue* consts below.
	optionalFieldsPresent uint64
}

// Bitmasks for "modified" flags for each field.
const (
	fieldModifiedHistogramValueCount = uint64(1 << iota)
	fieldModifiedHistogramValueSum
	fieldModifiedHistogramValueMin
	fieldModifiedHistogramValueMax
	fieldModifiedHistogramValueBucketCounts
)

// Bitmasks for "present" flags for optional fields.
const (
	fieldPresentHistogramValueSum = uint64(1 << iota)
	fieldPresentHistogramValueMin
	fieldPresentHistogramValueMax
)

// Init must be called once, before the HistogramValue is used.
func (s *HistogramValue) Init() {
	s.init(nil, 0)
}

func NewHistogramValue() *HistogramValue {
	var s HistogramValue
	s.init(nil, 0)
	return &s
}

func (s *HistogramValue) init(parentModifiedFields *modifiedFields, parentModifiedBit uint64) {
	s.modifiedFields.parent = parentModifiedFields
	s.modifiedFields.parentBit = parentModifiedBit

	s.bucketCounts.init(&s.modifiedFields, fieldModifiedHistogramValueBucketCounts)
}

func (s *HistogramValue) Count() int64 {
	return s.count
}

// SetCount sets the value of Count field.
func (s *HistogramValue) SetCount(v int64) {
	if !pkg.Int64Equal(s.count, v) {
		s.count = v
		s.markCountModified()
	}
}

func (s *HistogramValue) markCountModified() {
	s.modifiedFields.markModified(fieldModifiedHistogramValueCount)
}

// IsCountModified returns true the value of Count field was modified since
// HistogramValue was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *HistogramValue) IsCountModified() bool {
	return s.modifiedFields.mask&fieldModifiedHistogramValueCount != 0
}

func (s *HistogramValue) Sum() float64 {
	return s.sum
}

// SetSum sets the value of Sum field.
func (s *HistogramValue) SetSum(v float64) {
	if !pkg.Float64Equal(s.sum, v) || s.optionalFieldsPresent&fieldPresentHistogramValueSum == 0 {
		s.sum = v
		s.markSumModified()
		s.optionalFieldsPresent |= fieldPresentHistogramValueSum
	}
}

// UnsetSum unsets the precense flag of Sum field. A subsequent HasSum() will return false.
func (s *HistogramValue) UnsetSum() {
	if s.optionalFieldsPresent&fieldPresentHistogramValueSum != 0 {
		s.optionalFieldsPresent &= ^fieldPresentHistogramValueSum
		s.markSumModified()
	}
}

// HasSum returns true if the presence flag Sum field is set and false if it is unset.
func (s *HistogramValue) HasSum() bool {
	return s.optionalFieldsPresent&fieldPresentHistogramValueSum != 0
}

func (s *HistogramValue) markSumModified() {
	s.modifiedFields.markModified(fieldModifiedHistogramValueSum)
}

// IsSumModified returns true the value of Sum field was modified since
// HistogramValue was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *HistogramValue) IsSumModified() bool {
	return s.modifiedFields.mask&fieldModifiedHistogramValueSum != 0
}

func (s *HistogramValue) Min() float64 {
	return s.min
}

// SetMin sets the value of Min field.
func (s *HistogramValue) SetMin(v float64) {
	if !pkg.Float64Equal(s.min, v) || s.optionalFieldsPresent&fieldPresentHistogramValueMin == 0 {
		s.min = v
		s.markMinModified()
		s.optionalFieldsPresent |= fieldPresentHistogramValueMin
	}
}

// UnsetMin unsets the precense flag of Min field. A subsequent HasMin() will return false.
func (s *HistogramValue) UnsetMin() {
	if s.optionalFieldsPresent&fieldPresentHistogramValueMin != 0 {
		s.optionalFieldsPresent &= ^fieldPresentHistogramValueMin
		s.markMinModified()
	}
}

// HasMin returns true if the presence flag Min field is set and false if it is unset.
func (s *HistogramValue) HasMin() bool {
	return s.optionalFieldsPresent&fieldPresentHistogramValueMin != 0
}

func (s *HistogramValue) markMinModified() {
	s.modifiedFields.markModified(fieldModifiedHistogramValueMin)
}

// IsMinModified returns true the value of Min field was modified since
// HistogramValue was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *HistogramValue) IsMinModified() bool {
	return s.modifiedFields.mask&fieldModifiedHistogramValueMin != 0
}

func (s *HistogramValue) Max() float64 {
	return s.max
}

// SetMax sets the value of Max field.
func (s *HistogramValue) SetMax(v float64) {
	if !pkg.Float64Equal(s.max, v) || s.optionalFieldsPresent&fieldPresentHistogramValueMax == 0 {
		s.max = v
		s.markMaxModified()
		s.optionalFieldsPresent |= fieldPresentHistogramValueMax
	}
}

// UnsetMax unsets the precense flag of Max field. A subsequent HasMax() will return false.
func (s *HistogramValue) UnsetMax() {
	if s.optionalFieldsPresent&fieldPresentHistogramValueMax != 0 {
		s.optionalFieldsPresent &= ^fieldPresentHistogramValueMax
		s.markMaxModified()
	}
}

// HasMax returns true if the presence flag Max field is set and false if it is unset.
func (s *HistogramValue) HasMax() bool {
	return s.optionalFieldsPresent&fieldPresentHistogramValueMax != 0
}

func (s *HistogramValue) markMaxModified() {
	s.modifiedFields.markModified(fieldModifiedHistogramValueMax)
}

// IsMaxModified returns true the value of Max field was modified since
// HistogramValue was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *HistogramValue) IsMaxModified() bool {
	return s.modifiedFields.mask&fieldModifiedHistogramValueMax != 0
}

func (s *HistogramValue) BucketCounts() *Int64Array {
	return &s.bucketCounts
}

// IsBucketCountsModified returns true the value of BucketCounts field was modified since
// HistogramValue was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *HistogramValue) IsBucketCountsModified() bool {
	return s.modifiedFields.mask&fieldModifiedHistogramValueBucketCounts != 0
}

// ByteSize returns approximate memory usage in bytes. Used to calculate
// memory used by dictionaries.
func (s *HistogramValue) byteSize() uint {
	return uint(unsafe.Sizeof(*s)) +
		s.bucketCounts.byteSize() + 0
}

func copyHistogramValue(dst *HistogramValue, src *HistogramValue) {
	dst.SetCount(src.count)
	if src.HasSum() {
		dst.SetSum(src.sum)
	} else {
		dst.UnsetSum()
	}

	if src.HasMin() {
		dst.SetMin(src.min)
	} else {
		dst.UnsetMin()
	}

	if src.HasMax() {
		dst.SetMax(src.max)
	} else {
		dst.UnsetMax()
	}

	copyInt64Array(&dst.bucketCounts, &src.bucketCounts)
}

// CopyFrom() performs a deep copy from src.
func (s *HistogramValue) CopyFrom(src *HistogramValue) {
	copyHistogramValue(s, src)
}

func (s *HistogramValue) markParentModified() {
	s.modifiedFields.parent.markModified(s.modifiedFields.parentBit)
}

func (s *HistogramValue) markUnmodified() {
	s.modifiedFields.markUnmodified()
	s.bucketCounts.markUnmodified()
}

// IsEqual performs deep comparison and returns true if struct is equal to val.
func (e *HistogramValue) IsEqual(val *HistogramValue) bool {
	if !pkg.Int64Equal(e.count, val.count) {
		return false
	}
	if !pkg.Float64Equal(e.sum, val.sum) {
		return false
	}
	if !pkg.Float64Equal(e.min, val.min) {
		return false
	}
	if !pkg.Float64Equal(e.max, val.max) {
		return false
	}
	if !e.bucketCounts.IsEqual(&val.bucketCounts) {
		return false
	}

	return true
}

func HistogramValueEqual(left, right *HistogramValue) bool {
	return left.IsEqual(right)
}

// CmpHistogramValue performs deep comparison and returns an integer that
// will be 0 if left == right, negative if left < right, positive if left > right.
func CmpHistogramValue(left, right *HistogramValue) int {
	if left == nil {
		if right == nil {
			return 0
		}
		return -1
	}
	if right == nil {
		return 1
	}

	if c := pkg.Int64Compare(left.count, right.count); c != 0 {
		return c
	}
	if c := pkg.Float64Compare(left.sum, right.sum); c != 0 {
		return c
	}
	if c := pkg.Float64Compare(left.min, right.min); c != 0 {
		return c
	}
	if c := pkg.Float64Compare(left.max, right.max); c != 0 {
		return c
	}
	if c := CmpInt64Array(&left.bucketCounts, &right.bucketCounts); c != 0 {
		return c
	}

	return 0
}

// HistogramValueEncoder implements encoding of HistogramValue
type HistogramValueEncoder struct {
	buf     pkg.BitsWriter
	limiter *pkg.SizeLimiter

	// forceModifiedFields is set to true if the next encoding operation
	// must write all fields, whether they are modified or no.
	// This is used after frame restarts so that the data can be decoded
	// from the frame start.
	forceModifiedFields bool

	countEncoder        encoders.Int64Encoder
	sumEncoder          encoders.Float64Encoder
	minEncoder          encoders.Float64Encoder
	maxEncoder          encoders.Float64Encoder
	bucketCountsEncoder Int64ArrayEncoder

	keepFieldMask uint64
	fieldCount    uint
}

func (e *HistogramValueEncoder) Init(state *WriterState, columns *pkg.WriteColumnSet) error {
	state.HistogramValueEncoder = e
	e.limiter = &state.limiter

	if state.OverrideSchema != nil {
		overrideSchema, ok := state.OverrideSchema.Structs["HistogramValue"]
		if !ok || overrideSchema == nil {
			return fmt.Errorf("cannot find struct in override schema: %s", "HistogramValue")
		}

		// Number of fields in the target schema.
		e.fieldCount = uint(len(overrideSchema.Fields))

		// Set that many 1 bits in the keepFieldMask. All fields with higher number
		// will be skipped when encoding.
		e.keepFieldMask = ^(^uint64(0) << e.fieldCount)
	} else {
		// Keep all fields when encoding.
		e.fieldCount = 5
		e.keepFieldMask = ^uint64(0)
	}

	if e.fieldCount <= 0 {
		return nil // Count and subsequent fields are skipped.
	}
	if err := e.countEncoder.Init(e.limiter, columns.AddSubColumn()); err != nil {
		return err
	}
	if e.fieldCount <= 1 {
		return nil // Sum and subsequent fields are skipped.
	}
	if err := e.sumEncoder.Init(e.limiter, columns.AddSubColumn()); err != nil {
		return err
	}
	if e.fieldCount <= 2 {
		return nil // Min and subsequent fields are skipped.
	}
	if err := e.minEncoder.Init(e.limiter, columns.AddSubColumn()); err != nil {
		return err
	}
	if e.fieldCount <= 3 {
		return nil // Max and subsequent fields are skipped.
	}
	if err := e.maxEncoder.Init(e.limiter, columns.AddSubColumn()); err != nil {
		return err
	}
	if e.fieldCount <= 4 {
		return nil // BucketCounts and subsequent fields are skipped.
	}
	if err := e.bucketCountsEncoder.Init(state, columns.AddSubColumn()); err != nil {
		return err
	}

	return nil
}

func (e *HistogramValueEncoder) Reset() {
	// Since we are resetting the state of encoder make sure the next Encode()
	// call forcedly writes all fields and does not attempt to skip.
	e.forceModifiedFields = true
	e.countEncoder.Reset()
	e.sumEncoder.Reset()
	e.minEncoder.Reset()
	e.maxEncoder.Reset()
	e.bucketCountsEncoder.Reset()
}

// Encode encodes val into buf
func (e *HistogramValueEncoder) Encode(val *HistogramValue) {
	oldLen := e.buf.BitCount()

	// Mask that describes what fields are encoded. Start with all modified fields.
	fieldMask := val.modifiedFields.mask

	// If forceModifiedFields we need to set to 1 all bits so that we
	// force writing of all fields.
	if e.forceModifiedFields {
		fieldMask =
			fieldModifiedHistogramValueCount |
				fieldModifiedHistogramValueSum |
				fieldModifiedHistogramValueMin |
				fieldModifiedHistogramValueMax |
				fieldModifiedHistogramValueBucketCounts | 0
	}

	// Only write fields that we want to write. See Init() for keepFieldMask.
	fieldMask &= e.keepFieldMask

	// Write bits to indicate which fields follow.
	e.buf.WriteBits(fieldMask, e.fieldCount)

	// Write bits to indicate which optional fields are set.
	e.buf.WriteBits(val.optionalFieldsPresent, 3)

	// Encode modified, present fields.

	if fieldMask&fieldModifiedHistogramValueCount != 0 {
		// Encode Count
		e.countEncoder.Encode(val.count)
	}

	if fieldMask&fieldModifiedHistogramValueSum != 0 &&
		val.optionalFieldsPresent&fieldPresentHistogramValueSum != 0 {
		// Encode Sum
		e.sumEncoder.Encode(val.sum)
	}

	if fieldMask&fieldModifiedHistogramValueMin != 0 &&
		val.optionalFieldsPresent&fieldPresentHistogramValueMin != 0 {
		// Encode Min
		e.minEncoder.Encode(val.min)
	}

	if fieldMask&fieldModifiedHistogramValueMax != 0 &&
		val.optionalFieldsPresent&fieldPresentHistogramValueMax != 0 {
		// Encode Max
		e.maxEncoder.Encode(val.max)
	}

	if fieldMask&fieldModifiedHistogramValueBucketCounts != 0 {
		// Encode BucketCounts
		e.bucketCountsEncoder.Encode(&val.bucketCounts)
	}

	// Account written bits in the limiter.
	newLen := e.buf.BitCount()
	e.limiter.AddFrameBits(newLen - oldLen)

	// Mark all fields non-modified so that next Encode() correctly
	// encodes only fields that change after this.
	val.modifiedFields.mask = 0
}

// CollectColumns collects all buffers from all encoders into buf.
func (e *HistogramValueEncoder) CollectColumns(columnSet *pkg.WriteColumnSet) {
	columnSet.SetBits(&e.buf)

	if e.fieldCount <= 0 {
		return // Count and subsequent fields are skipped.
	}
	e.countEncoder.CollectColumns(columnSet.At(0))
	if e.fieldCount <= 1 {
		return // Sum and subsequent fields are skipped.
	}
	e.sumEncoder.CollectColumns(columnSet.At(1))
	if e.fieldCount <= 2 {
		return // Min and subsequent fields are skipped.
	}
	e.minEncoder.CollectColumns(columnSet.At(2))
	if e.fieldCount <= 3 {
		return // Max and subsequent fields are skipped.
	}
	e.maxEncoder.CollectColumns(columnSet.At(3))
	if e.fieldCount <= 4 {
		return // BucketCounts and subsequent fields are skipped.
	}
	e.bucketCountsEncoder.CollectColumns(columnSet.At(4))
}

// HistogramValueDecoder implements decoding of HistogramValue
type HistogramValueDecoder struct {
	buf        pkg.BitsReader
	column     *pkg.ReadableColumn
	lastValPtr *HistogramValue
	lastVal    HistogramValue
	fieldCount uint

	countDecoder        encoders.Int64Decoder
	sumDecoder          encoders.Float64Decoder
	minDecoder          encoders.Float64Decoder
	maxDecoder          encoders.Float64Decoder
	bucketCountsDecoder Int64ArrayDecoder
}

// Init is called once in the lifetime of the stream.
func (d *HistogramValueDecoder) Init(state *ReaderState, columns *pkg.ReadColumnSet) error {
	state.HistogramValueDecoder = d

	if state.OverrideSchema != nil {
		overrideSchema, ok := state.OverrideSchema.Structs["HistogramValue"]
		if !ok || overrideSchema == nil {
			return fmt.Errorf("cannot find struct in override schema: %s", "HistogramValue")
		}

		// Number of fields in the target schema.
		d.fieldCount = uint(len(overrideSchema.Fields))
	} else {
		// Keep all fields when encoding.
		d.fieldCount = 5
	}

	d.column = columns.Column()

	d.lastVal.init(nil, 0)
	d.lastValPtr = &d.lastVal

	var err error

	if d.fieldCount <= 0 {
		return nil // Count and subsequent fields are skipped.
	}
	err = d.countDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 1 {
		return nil // Sum and subsequent fields are skipped.
	}
	err = d.sumDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 2 {
		return nil // Min and subsequent fields are skipped.
	}
	err = d.minDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 3 {
		return nil // Max and subsequent fields are skipped.
	}
	err = d.maxDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 4 {
		return nil // BucketCounts and subsequent fields are skipped.
	}
	err = d.bucketCountsDecoder.Init(state, columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

// Continue is called at the start of the frame to continue decoding column data.
// This should set the decoder's source buffer, so the new decoding continues from
// the supplied column data. This should NOT reset the internal state of the decoder,
// since columns can cross frame boundaries and the new column data is considered
// continuation of that same column in the previous frame.
func (d *HistogramValueDecoder) Continue() {
	d.buf.Reset(d.column.Data())

	if d.fieldCount <= 0 {
		return // Count and subsequent fields are skipped.
	}
	d.countDecoder.Continue()
	if d.fieldCount <= 1 {
		return // Sum and subsequent fields are skipped.
	}
	d.sumDecoder.Continue()
	if d.fieldCount <= 2 {
		return // Min and subsequent fields are skipped.
	}
	d.minDecoder.Continue()
	if d.fieldCount <= 3 {
		return // Max and subsequent fields are skipped.
	}
	d.maxDecoder.Continue()
	if d.fieldCount <= 4 {
		return // BucketCounts and subsequent fields are skipped.
	}
	d.bucketCountsDecoder.Continue()
}

func (d *HistogramValueDecoder) Reset() {
	d.countDecoder.Reset()
	d.sumDecoder.Reset()
	d.minDecoder.Reset()
	d.maxDecoder.Reset()
	d.bucketCountsDecoder.Reset()
}

func (d *HistogramValueDecoder) Decode(dstPtr *HistogramValue) error {
	val := dstPtr

	var err error

	// Read bits that indicate which fields follow.
	val.modifiedFields.mask = d.buf.ReadBits(d.fieldCount)

	// Write bits to indicate which optional fields are set.
	val.optionalFieldsPresent = d.buf.ReadBits(3)

	if val.modifiedFields.mask&fieldModifiedHistogramValueCount != 0 {
		// Field is changed and is present, decode it.
		err = d.countDecoder.Decode(&val.count)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedHistogramValueSum != 0 &&
		val.optionalFieldsPresent&fieldPresentHistogramValueSum != 0 {
		// Field is changed and is present, decode it.
		err = d.sumDecoder.Decode(&val.sum)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedHistogramValueMin != 0 &&
		val.optionalFieldsPresent&fieldPresentHistogramValueMin != 0 {
		// Field is changed and is present, decode it.
		err = d.minDecoder.Decode(&val.min)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedHistogramValueMax != 0 &&
		val.optionalFieldsPresent&fieldPresentHistogramValueMax != 0 {
		// Field is changed and is present, decode it.
		err = d.maxDecoder.Decode(&val.max)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedHistogramValueBucketCounts != 0 {
		// Field is changed and is present, decode it.
		err = d.bucketCountsDecoder.Decode(&val.bucketCounts)
		if err != nil {
			return err
		}
	}

	return nil
}
