// Code generated by stefgen. DO NOT EDIT.
package oteltef

import (
	"bytes"
	"fmt"
	"io"
	"math/rand/v2"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/splunk/stef/go/pkg"
)

// genMetricsRecords generates a number of records pseudo-randomly
// using the supplied Rand generator. Generated records will be always
// the same for the same input state of Rand generator.
func genMetricsRecords(random *rand.Rand) (records []Metrics) {
	const recCount = 1000
	var record Metrics
	record.Init()

	records = make([]Metrics, recCount)
	for i := 0; i < recCount; i++ {
		record.mutateRandom(random)
		records[i].Init()
		records[i].CopyFrom(&record)
	}

	return records
}

func TestMetricsWriteRead(t *testing.T) {
	opts := []pkg.WriterOptions{
		{},
		{Compression: pkg.CompressionZstd},
		{MaxUncompressedFrameByteSize: 500},
		{MaxTotalDictSize: 500},
		{
			Compression:                  pkg.CompressionZstd,
			MaxUncompressedFrameByteSize: 500,
			MaxTotalDictSize:             500,
		},
		{FrameRestartFlags: pkg.RestartDictionaries},
		{FrameRestartFlags: pkg.RestartCodecs},
		{FrameRestartFlags: pkg.RestartDictionaries | pkg.RestartCodecs},
		{FrameRestartFlags: pkg.RestartCompression, Compression: pkg.CompressionZstd},
		{
			FrameRestartFlags: pkg.RestartDictionaries | pkg.RestartCodecs | pkg.RestartCompression,
			Compression:       pkg.CompressionZstd,
		},
		{
			FrameRestartFlags:            pkg.RestartCodecs,
			MaxUncompressedFrameByteSize: 500,
		},
	}

	// Choose a seed (non-pseudo) randomly. We will print the seed
	// on failure for easy reproduction.
	seed1 := uint64(time.Now().UnixNano())
	random := rand.New(rand.NewPCG(seed1, 0))

	for _, opt := range opts {
		t.Run(
			"", func(t *testing.T) {
				succeeded := false
				defer func() {
					if !succeeded {
						fmt.Printf("Test failed with seed %v\n", seed1)
					}
				}()

				buf := &pkg.MemChunkWriter{}
				writer, err := NewMetricsWriter(buf, opt)
				require.NoError(t, err, "seed %v", seed1)

				// Generate records pseudo-randomly
				records := genMetricsRecords(random)
				// Write the records
				for i := 0; i < len(records); i++ {
					writer.Record.CopyFrom(&records[i])
					err = writer.Write()
					require.NoError(t, err, "record %d seed %v", i, seed1)
				}
				err = writer.Flush()
				require.NoError(t, err, "seed %v", seed1)

				// Read the records and compare to written.
				reader, err := NewMetricsReader(bytes.NewBuffer(buf.Bytes()))
				require.NoError(t, err, "seed %v", seed1)

				for i := 0; i < len(records); i++ {
					err := reader.Read(pkg.ReadOptions{})
					require.NoError(t, err, "record %d seed %v", i, seed1)
					require.NotNil(t, reader.Record, "record %d seed %v", i, seed1)
					require.True(t, reader.Record.IsEqual(&records[i]), "record %d seed %v", i, seed1)
				}
				err = reader.Read(pkg.ReadOptions{})
				require.Error(t, io.EOF, seed1)

				succeeded = true
			},
		)
	}
}
