// Code generated by stefgen. DO NOT EDIT.
package oteltef

import (
	"math/rand/v2"

	"strings"
	"unsafe"

	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/encoders"
)

var _ = (*encoders.StringEncoder)(nil)
var _ = (*strings.Builder)(nil)

// QuantileValueArray is a variable size array.
type QuantileValueArray struct {
	elems []*QuantileValue

	parentModifiedFields *modifiedFields
	parentModifiedBit    uint64
}

func (e *QuantileValueArray) init(parentModifiedFields *modifiedFields, parentModifiedBit uint64) {
	e.parentModifiedFields = parentModifiedFields
	e.parentModifiedBit = parentModifiedBit
}

// Clone() creates a deep copy of QuantileValueArray
func (e *QuantileValueArray) Clone() QuantileValueArray {
	var clone QuantileValueArray
	copyQuantileValueArray(&clone, e)
	return clone
}

// ByteSize returns approximate memory usage in bytes. Used to calculate
// memory used by dictionaries.
func (e *QuantileValueArray) byteSize() uint {
	if len(e.elems) == 0 {
		return 0
	}
	// TODO: add size of elements if they are clonable.
	size := uint(unsafe.Sizeof(e.elems[0]))*uint(len(e.elems)) + uint(unsafe.Sizeof(e))

	for i := range e.elems {
		size += e.elems[i].byteSize()
	}
	return size
}

// Append a new element at the end of the array.
func (e *QuantileValueArray) Append(val *QuantileValue) {
	e.elems = append(e.elems, val)
	e.markModified()
}

func (e *QuantileValueArray) markModified() {
	e.parentModifiedFields.markModified(e.parentModifiedBit)
}

func (e *QuantileValueArray) markUnmodified() {
	e.parentModifiedFields.markUnmodified()
}

func (e *QuantileValueArray) markModifiedRecursively() {
	for i := 0; i < len(e.elems); i++ {
		e.elems[i].markModifiedRecursively()
	}

}

func (e *QuantileValueArray) markUnmodifiedRecursively() {
	for i := 0; i < len(e.elems); i++ {
		e.elems[i].markUnmodifiedRecursively()
	}

}

// markDiffModified marks fields in each element of this array modified if they differ from
// the corresponding fields in v.
func (e *QuantileValueArray) markDiffModified(v *QuantileValueArray) (modified bool) {
	if len(e.elems) != len(v.elems) {
		// Array lengths are different, so they are definitely different.
		modified = true
	}

	// Scan the elements and mark them as modified if they are different.
	minLen := min(len(e.elems), len(v.elems))
	for i := 0; i < minLen; i++ {
		if e.elems[i].markDiffModified(v.elems[i]) {
			modified = true
		}
	}

	// Mark the rest of the elements as modified.
	for i := minLen; i < len(e.elems); i++ {
		e.elems[i].markModifiedRecursively()
	}

	if modified {
		e.markModified()
	}

	return modified
}

func copyQuantileValueArray(dst *QuantileValueArray, src *QuantileValueArray) {
	isModified := false

	minLen := min(len(dst.elems), len(src.elems))
	if len(dst.elems) != len(src.elems) {
		dst.elems = pkg.EnsureLen(dst.elems, len(src.elems))
		isModified = true
	}

	i := 0

	// Copy elements in the part of the array that already had the necessary room.
	for ; i < minLen; i++ {
		copyQuantileValue(dst.elems[i], src.elems[i])
		isModified = true
	}
	if minLen < len(dst.elems) {
		isModified = true
		// Need to allocate new elements for the part of the array that has grown.
		// Allocate all new elements at once.
		elems := make([]QuantileValue, len(dst.elems)-minLen)
		for j := range elems {
			// Init the element.
			elems[j].init(dst.parentModifiedFields, dst.parentModifiedBit)
			// Point to the allocated element.
			dst.elems[i+j] = &elems[j]
			// Copy the element.
			copyQuantileValue(dst.elems[i+j], src.elems[i+j])
		}
	}
	if isModified {
		dst.markModified()
	}
}

// Len returns the number of elements in the array.
func (e *QuantileValueArray) Len() int {
	return len(e.elems)
}

// At returns element at index i.
func (m *QuantileValueArray) At(i int) *QuantileValue {
	return m.elems[i]
}

// EnsureLen ensures the length of the array is equal to newLen.
// It will grow or shrink the array if needed.
func (e *QuantileValueArray) EnsureLen(newLen int) {
	oldLen := len(e.elems)
	if newLen > oldLen {
		// Grow the array
		e.elems = append(e.elems, make([]*QuantileValue, newLen-oldLen)...)
		e.markModified()
		// Initialize newlly added elements.
		for ; oldLen < newLen; oldLen++ {
			e.elems[oldLen] = new(QuantileValue)
			e.elems[oldLen].init(e.parentModifiedFields, e.parentModifiedBit)
		}
	} else if oldLen > newLen {
		// Shrink it
		e.elems = e.elems[:newLen]
		e.markModified()
	}
}

// IsEqual performs deep comparison and returns true if array is equal to val.
func (e *QuantileValueArray) IsEqual(val *QuantileValueArray) bool {
	if len(e.elems) != len(val.elems) {
		return false
	}
	for i := range e.elems {
		if !e.elems[i].IsEqual(val.elems[i]) {
			return false
		}
	}
	return true
}

// CmpQuantileValueArray performs deep comparison and returns an integer that
// will be 0 if left == right, negative if left < right, positive if left > right.
func CmpQuantileValueArray(left, right *QuantileValueArray) int {
	c := len(left.elems) - len(right.elems)
	if c != 0 {
		return c
	}
	for i := range left.elems {
		fc := CmpQuantileValue(left.elems[i], right.elems[i])
		if fc < 0 {
			return -1
		}
		if fc > 0 {
			return 1
		}
	}
	return 0
}

// mutateRandom mutates fields in a random, deterministic manner using
// random parameter as a deterministic generator.
func (a *QuantileValueArray) mutateRandom(random *rand.Rand) {
	if random.IntN(20) == 0 {
		a.EnsureLen(a.Len() + 1)
	}
	if random.IntN(20) == 0 && a.Len() > 0 {
		a.EnsureLen(a.Len() - 1)
	}

	for i := range a.elems {
		_ = i
		if random.IntN(2*len(a.elems)) == 0 {
			a.elems[i].mutateRandom(random)
		}
	}
}

type QuantileValueArrayEncoder struct {
	buf         pkg.BitsWriter
	limiter     *pkg.SizeLimiter
	elemEncoder *QuantileValueEncoder
	isRecursive bool
	state       *WriterState
	// lastValStack are last encoded values stacked by the level of recursion.
	lastValStack QuantileValueArrayEncoderLastValStack
}
type QuantileValueArrayEncoderLastValStack []*QuantileValueArrayEncoderLastValElem

func (s *QuantileValueArrayEncoderLastValStack) init() {
	// We need one top-level element in the stack to store the last value initially.
	s.addOnTop()
}

func (s *QuantileValueArrayEncoderLastValStack) reset() {
	// Reset all elements in the stack.
	t := (*s)[:cap(*s)]
	for i := 0; i < len(t); i++ {
		t[i].reset()
	}
	// Reset the stack to have one element for top-level.
	*s = (*s)[:1]
}

func (s *QuantileValueArrayEncoderLastValStack) top() *QuantileValueArrayEncoderLastValElem {
	return (*s)[len(*s)-1]
}

func (s *QuantileValueArrayEncoderLastValStack) addOnTopSlow() {
	elem := &QuantileValueArrayEncoderLastValElem{}
	elem.init()
	*s = append(*s, elem)
	t := (*s)[0:cap(*s)]
	for i := len(*s); i < len(t); i++ {
		// Ensure that all elements in the stack are initialized.
		t[i] = &QuantileValueArrayEncoderLastValElem{}
		t[i].init()
	}
}

func (s *QuantileValueArrayEncoderLastValStack) addOnTop() {
	if len(*s) < cap(*s) {
		*s = (*s)[:len(*s)+1]
		return
	}
	s.addOnTopSlow()
}

func (s *QuantileValueArrayEncoderLastValStack) removeFromTop() {
	*s = (*s)[:len(*s)-1]
}

type QuantileValueArrayEncoderLastValElem struct {
	prevLen        int
	elem           QuantileValue
	modifiedFields modifiedFields
}

func (e *QuantileValueArrayEncoderLastValElem) init() {
	e.elem.init(&e.modifiedFields, 1)
}

func (e *QuantileValueArrayEncoderLastValElem) reset() {
	e.elem = QuantileValue{}
	e.prevLen = 0
}

func (e *QuantileValueArrayEncoder) Init(state *WriterState, columns *pkg.WriteColumnSet) error {
	e.state = state
	e.limiter = &state.limiter

	// Remember this encoder in the state so that we can detect recursion.
	if state.QuantileValueArrayEncoder != nil {
		panic("cannot initialize QuantileValueArrayEncoder: already initialized")
	}
	state.QuantileValueArrayEncoder = e
	defer func() { state.QuantileValueArrayEncoder = nil }()

	if state.QuantileValueEncoder != nil {
		// Recursion detected, use the existing encoder.
		e.elemEncoder = state.QuantileValueEncoder
		e.isRecursive = true
	} else {
		e.elemEncoder = new(QuantileValueEncoder)
		if err := e.elemEncoder.Init(state, columns.AddSubColumn()); err != nil {
			return err
		}
	}
	e.lastValStack.init()

	return nil
}

func (e *QuantileValueArrayEncoder) Reset() {
	if !e.isRecursive {
		e.elemEncoder.Reset()
	}

	e.lastValStack.reset()
}

func (e *QuantileValueArrayEncoder) Encode(arr *QuantileValueArray) {
	lastVal := e.lastValStack.top()
	e.lastValStack.addOnTop()
	defer func() { e.lastValStack.removeFromTop() }()

	newLen := len(arr.elems)
	oldBitLen := e.buf.BitCount()

	lenDelta := newLen - lastVal.prevLen
	lastVal.prevLen = newLen

	e.buf.WriteVarintCompact(int64(lenDelta))

	if newLen > 0 {
		for i := 0; i < newLen; i++ {
			if i == 0 {
				// Compute and mark fields that are modified compared to the last encoded value.
				arr.elems[i].markDiffModified(&lastVal.elem)
			} else {
				// Compute and mark fields that are modified compared to the previous element.
				arr.elems[i].markDiffModified(arr.elems[i-1])
			}

			// Encode the element.
			e.elemEncoder.Encode(arr.elems[i])
		}
		// Remember last encoded element.
		copyQuantileValue(&lastVal.elem, arr.elems[len(arr.elems)-1])
	}

	// Account written bits in the limiter.
	newBitLen := e.buf.BitCount()
	e.limiter.AddFrameBits(newBitLen - oldBitLen)
}

func (e *QuantileValueArrayEncoder) CollectColumns(columnSet *pkg.WriteColumnSet) {
	columnSet.SetBits(&e.buf)
	if !e.isRecursive {
		e.elemEncoder.CollectColumns(columnSet.At(0))
	}
}

type QuantileValueArrayDecoder struct {
	buf         pkg.BitsReader
	column      *pkg.ReadableColumn
	elemDecoder *QuantileValueDecoder
	isRecursive bool
	// lastValStack are last decoded values stacked by the level of recursion.
	lastValStack QuantileValueArrayDecoderLastValStack
}
type QuantileValueArrayDecoderLastValStack []*QuantileValueArrayDecoderLastValElem

func (s *QuantileValueArrayDecoderLastValStack) init() {
	// We need one top-level element in the stack to store the last value initially.
	s.addOnTop()
}

func (s *QuantileValueArrayDecoderLastValStack) reset() {
	// Reset all elements in the stack.
	t := (*s)[:cap(*s)]
	for i := 0; i < len(t); i++ {
		t[i].reset()
	}
	// Reset the stack to have one element for top-level.
	*s = (*s)[:1]
}

func (s *QuantileValueArrayDecoderLastValStack) top() *QuantileValueArrayDecoderLastValElem {
	return (*s)[len(*s)-1]
}

func (s *QuantileValueArrayDecoderLastValStack) addOnTopSlow() {
	elem := &QuantileValueArrayDecoderLastValElem{}
	elem.init()
	*s = append(*s, elem)
	t := (*s)[0:cap(*s)]
	for i := len(*s); i < len(t); i++ {
		// Ensure that all elements in the stack are initialized.
		t[i] = &QuantileValueArrayDecoderLastValElem{}
		t[i].init()
	}
}

func (s *QuantileValueArrayDecoderLastValStack) addOnTop() {
	if len(*s) < cap(*s) {
		*s = (*s)[:len(*s)+1]
		return
	}
	s.addOnTopSlow()
}

func (s *QuantileValueArrayDecoderLastValStack) removeFromTop() {
	*s = (*s)[:len(*s)-1]
}

type QuantileValueArrayDecoderLastValElem struct {
	prevLen int
	elem    QuantileValue
}

func (e *QuantileValueArrayDecoderLastValElem) init() {
}

func (e *QuantileValueArrayDecoderLastValElem) reset() {
	e.prevLen = 0

	e.elem = QuantileValue{}

}

// Init is called once in the lifetime of the stream.
func (d *QuantileValueArrayDecoder) Init(state *ReaderState, columns *pkg.ReadColumnSet) error {
	d.column = columns.Column()
	// Remember this encoder in the state so that we can detect recursion.
	if state.QuantileValueArrayDecoder != nil {
		panic("cannot initialize QuantileValueArrayDecoder: already initialized")
	}
	state.QuantileValueArrayDecoder = d
	defer func() { state.QuantileValueArrayDecoder = nil }()

	if state.QuantileValueDecoder != nil {
		d.elemDecoder = state.QuantileValueDecoder
		d.isRecursive = true
	} else {
		d.elemDecoder = new(QuantileValueDecoder)
		if err := d.elemDecoder.Init(state, columns.AddSubColumn()); err != nil {
			return err
		}
	}
	d.lastValStack.init()

	return nil
}

// Continue is called at the start of the frame to continue decoding column data.
// This should set the decoder's source buffer, so the new decoding continues from
// the supplied column data. This should NOT reset the internal state of the decoder,
// since columns can cross frame boundaries and the new column data is considered
// continuation of that same column in the previous frame.
func (d *QuantileValueArrayDecoder) Continue() {
	d.buf.Reset(d.column.Data())
	if !d.isRecursive {
		d.elemDecoder.Continue()
	}
}

func (d *QuantileValueArrayDecoder) Reset() {
	if !d.isRecursive {
		d.elemDecoder.Reset()
	}
	d.lastValStack.reset()
}

func (d *QuantileValueArrayDecoder) Decode(dst *QuantileValueArray) error {
	lastVal := d.lastValStack.top()
	d.lastValStack.addOnTop()
	defer func() { d.lastValStack.removeFromTop() }()

	lenDelta := d.buf.ReadVarintCompact()

	newLen := lastVal.prevLen + int(lenDelta)
	lastVal.prevLen = newLen

	dst.EnsureLen(newLen)

	for i := 0; i < newLen; i++ {
		err := d.elemDecoder.Decode(&lastVal.elem)
		if err != nil {
			return err
		}
		copyQuantileValue(dst.elems[i], &lastVal.elem)
	}

	return nil
}
