// Code generated by stefgen. DO NOT EDIT.
package oteltef

import (
	"bytes"
	"fmt"
	"math/rand/v2"
	"strings"
	"unsafe"

	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/encoders"
	"github.com/splunk/stef/go/pkg/schema"
)

var _ = strings.Compare
var _ = encoders.StringEncoder{}
var _ = schema.WireSchema{}
var _ = bytes.NewBuffer

type QuantileValue struct {
	quantile float64
	value    float64

	// modifiedFields keeps track of which fields are modified.
	modifiedFields modifiedFields
}

const QuantileValueStructName = "QuantileValue"

// Bitmasks for "modified" flags for each field.
const (
	fieldModifiedQuantileValueQuantile = uint64(1 << iota)
	fieldModifiedQuantileValueValue
)

// Init must be called once, before the QuantileValue is used.
func (s *QuantileValue) Init() {
	s.init(nil, 0)
}

func NewQuantileValue() *QuantileValue {
	var s QuantileValue
	s.init(nil, 0)
	return &s
}

func (s *QuantileValue) init(parentModifiedFields *modifiedFields, parentModifiedBit uint64) {
	s.modifiedFields.parent = parentModifiedFields
	s.modifiedFields.parentBit = parentModifiedBit

}

func (s *QuantileValue) Quantile() float64 {
	return s.quantile
}

// SetQuantile sets the value of Quantile field.
func (s *QuantileValue) SetQuantile(v float64) {
	if !pkg.Float64Equal(s.quantile, v) {
		s.quantile = v
		s.markQuantileModified()
	}
}

func (s *QuantileValue) markQuantileModified() {
	s.modifiedFields.markModified(fieldModifiedQuantileValueQuantile)
}

// IsQuantileModified returns true the value of Quantile field was modified since
// QuantileValue was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *QuantileValue) IsQuantileModified() bool {
	return s.modifiedFields.mask&fieldModifiedQuantileValueQuantile != 0
}

func (s *QuantileValue) Value() float64 {
	return s.value
}

// SetValue sets the value of Value field.
func (s *QuantileValue) SetValue(v float64) {
	if !pkg.Float64Equal(s.value, v) {
		s.value = v
		s.markValueModified()
	}
}

func (s *QuantileValue) markValueModified() {
	s.modifiedFields.markModified(fieldModifiedQuantileValueValue)
}

// IsValueModified returns true the value of Value field was modified since
// QuantileValue was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *QuantileValue) IsValueModified() bool {
	return s.modifiedFields.mask&fieldModifiedQuantileValueValue != 0
}

func (s *QuantileValue) markModifiedRecursively() {

	s.modifiedFields.mask =
		fieldModifiedQuantileValueQuantile |
			fieldModifiedQuantileValueValue | 0
}

func (s *QuantileValue) markUnmodifiedRecursively() {

	if s.IsQuantileModified() {
	}

	if s.IsValueModified() {
	}

	s.modifiedFields.mask = 0
}

// markDiffModified marks fields in this struct modified if they differ from
// the corresponding fields in v.
func (s *QuantileValue) markDiffModified(v *QuantileValue) (modified bool) {
	if !pkg.Float64Equal(s.quantile, v.quantile) {
		s.markQuantileModified()
		modified = true
	}

	if !pkg.Float64Equal(s.value, v.value) {
		s.markValueModified()
		modified = true
	}

	return modified
}

func (s *QuantileValue) Clone() QuantileValue {
	return QuantileValue{
		quantile: s.quantile,
		value:    s.value,
	}
}

// ByteSize returns approximate memory usage in bytes. Used to calculate
// memory used by dictionaries.
func (s *QuantileValue) byteSize() uint {
	return uint(unsafe.Sizeof(*s)) +
		0
}

func copyQuantileValue(dst *QuantileValue, src *QuantileValue) {
	dst.SetQuantile(src.quantile)
	dst.SetValue(src.value)
}

// CopyFrom() performs a deep copy from src.
func (s *QuantileValue) CopyFrom(src *QuantileValue) {
	copyQuantileValue(s, src)
}

func (s *QuantileValue) markParentModified() {
	s.modifiedFields.parent.markModified(s.modifiedFields.parentBit)
}

func (s *QuantileValue) markUnmodified() {
	s.modifiedFields.markUnmodified()
}

// mutateRandom mutates fields in a random, deterministic manner using
// random parameter as a deterministic generator.
func (s *QuantileValue) mutateRandom(random *rand.Rand) {
	const fieldCount = max(2, 2) // At least 2 to ensure we don't recurse infinitely if there is only 1 field.
	if random.IntN(fieldCount) == 0 {
		s.SetQuantile(pkg.Float64Random(random))
	}
	if random.IntN(fieldCount) == 0 {
		s.SetValue(pkg.Float64Random(random))
	}
}

// IsEqual performs deep comparison and returns true if struct is equal to right.
func (s *QuantileValue) IsEqual(right *QuantileValue) bool {
	// Compare Quantile field.
	if !pkg.Float64Equal(s.quantile, right.quantile) {
		return false
	}
	// Compare Value field.
	if !pkg.Float64Equal(s.value, right.value) {
		return false
	}

	return true
}

func QuantileValueEqual(left, right *QuantileValue) bool {
	return left.IsEqual(right)
}

// CmpQuantileValue performs deep comparison and returns an integer that
// will be 0 if left == right, negative if left < right, positive if left > right.
func CmpQuantileValue(left, right *QuantileValue) int {
	if left == nil {
		if right == nil {
			return 0
		}
		return -1
	}
	if right == nil {
		return 1
	}

	// Compare Quantile field.
	if c := pkg.Float64Compare(left.quantile, right.quantile); c != 0 {
		return c
	}

	// Compare Value field.
	if c := pkg.Float64Compare(left.value, right.value); c != 0 {
		return c
	}

	return 0
}

// QuantileValueEncoder implements encoding of QuantileValue
type QuantileValueEncoder struct {
	buf     pkg.BitsWriter
	limiter *pkg.SizeLimiter

	// forceModifiedFields is set to true if the next encoding operation
	// must write all fields, whether they are modified or no.
	// This is used after frame restarts so that the data can be decoded
	// from the frame start.
	forceModifiedFields bool

	quantileEncoder encoders.Float64Encoder

	valueEncoder encoders.Float64Encoder

	keepFieldMask uint64
	fieldCount    uint
}

func (e *QuantileValueEncoder) Init(state *WriterState, columns *pkg.WriteColumnSet) error {
	// Remember this encoder in the state so that we can detect recursion.
	if state.QuantileValueEncoder != nil {
		panic("cannot initialize QuantileValueEncoder: already initialized")
	}
	state.QuantileValueEncoder = e
	defer func() { state.QuantileValueEncoder = nil }()

	e.limiter = &state.limiter

	if state.OverrideSchema != nil {
		fieldCount, ok := state.OverrideSchema.FieldCount("QuantileValue")
		if !ok {
			return fmt.Errorf("cannot find struct in override schema: %s", "QuantileValue")
		}

		// Number of fields in the target schema.
		e.fieldCount = fieldCount

		// Set that many 1 bits in the keepFieldMask. All fields with higher number
		// will be skipped when encoding.
		e.keepFieldMask = ^(^uint64(0) << e.fieldCount)
	} else {
		// Keep all fields when encoding.
		e.fieldCount = 2
		e.keepFieldMask = ^uint64(0)
	}

	var err error

	// Init encoder for Quantile field.
	if e.fieldCount <= 0 {
		// Quantile and all subsequent fields are skipped.
		return nil
	}
	err = e.quantileEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	// Init encoder for Value field.
	if e.fieldCount <= 1 {
		// Value and all subsequent fields are skipped.
		return nil
	}
	err = e.valueEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

func (e *QuantileValueEncoder) Reset() {
	// Since we are resetting the state of encoder make sure the next Encode()
	// call forcedly writes all fields and does not attempt to skip.
	e.forceModifiedFields = true
	e.quantileEncoder.Reset()
	e.valueEncoder.Reset()
}

// Encode encodes val into buf
func (e *QuantileValueEncoder) Encode(val *QuantileValue) {
	var bitCount uint

	// Mask that describes what fields are encoded. Start with all modified fields.
	fieldMask := val.modifiedFields.mask

	// If forceModifiedFields we need to set to 1 all bits so that we
	// force writing of all fields.
	if e.forceModifiedFields {
		fieldMask =
			fieldModifiedQuantileValueQuantile |
				fieldModifiedQuantileValueValue | 0
	}

	// Only write fields that we want to write. See Init() for keepFieldMask.
	fieldMask &= e.keepFieldMask

	// Write bits to indicate which fields follow.
	e.buf.WriteBits(fieldMask, e.fieldCount)
	bitCount += e.fieldCount

	// Encode modified, present fields.

	if fieldMask&fieldModifiedQuantileValueQuantile != 0 {
		// Encode Quantile
		e.quantileEncoder.Encode(val.quantile)
	}

	if fieldMask&fieldModifiedQuantileValueValue != 0 {
		// Encode Value
		e.valueEncoder.Encode(val.value)
	}

	// Account written bits in the limiter.
	e.limiter.AddFrameBits(bitCount)

	// Mark all fields non-modified so that next Encode() correctly
	// encodes only fields that change after this.
	val.modifiedFields.mask = 0
}

// CollectColumns collects all buffers from all encoders into buf.
func (e *QuantileValueEncoder) CollectColumns(columnSet *pkg.WriteColumnSet) {
	columnSet.SetBits(&e.buf)
	colIdx := 0

	// Collect Quantile field.
	if e.fieldCount <= 0 {
		return // Quantile and subsequent fields are skipped.
	}

	e.quantileEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++

	// Collect Value field.
	if e.fieldCount <= 1 {
		return // Value and subsequent fields are skipped.
	}

	e.valueEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++
}

// QuantileValueDecoder implements decoding of QuantileValue
type QuantileValueDecoder struct {
	buf        pkg.BitsReader
	column     *pkg.ReadableColumn
	lastValPtr *QuantileValue
	lastVal    QuantileValue
	fieldCount uint

	quantileDecoder encoders.Float64Decoder

	valueDecoder encoders.Float64Decoder
}

// Init is called once in the lifetime of the stream.
func (d *QuantileValueDecoder) Init(state *ReaderState, columns *pkg.ReadColumnSet) error {
	// Remember this decoder in the state so that we can detect recursion.
	if state.QuantileValueDecoder != nil {
		panic("cannot initialize QuantileValueDecoder: already initialized")
	}
	state.QuantileValueDecoder = d
	defer func() { state.QuantileValueDecoder = nil }()

	if state.OverrideSchema != nil {
		fieldCount, ok := state.OverrideSchema.FieldCount("QuantileValue")
		if !ok {
			return fmt.Errorf("cannot find struct in override schema: %s", "QuantileValue")
		}

		// Number of fields in the target schema.
		d.fieldCount = fieldCount
	} else {
		// Keep all fields when encoding.
		d.fieldCount = 2
	}

	d.column = columns.Column()

	d.lastVal.init(nil, 0)
	d.lastValPtr = &d.lastVal

	var err error

	if d.fieldCount <= 0 {
		return nil // Quantile and subsequent fields are skipped.
	}
	err = d.quantileDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 1 {
		return nil // Value and subsequent fields are skipped.
	}
	err = d.valueDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

// Continue is called at the start of the frame to continue decoding column data.
// This should set the decoder's source buffer, so the new decoding continues from
// the supplied column data. This should NOT reset the internal state of the decoder,
// since columns can cross frame boundaries and the new column data is considered
// continuation of that same column in the previous frame.
func (d *QuantileValueDecoder) Continue() {
	d.buf.Reset(d.column.Data())

	if d.fieldCount <= 0 {
		return // Quantile and subsequent fields are skipped.
	}
	d.quantileDecoder.Continue()
	if d.fieldCount <= 1 {
		return // Value and subsequent fields are skipped.
	}
	d.valueDecoder.Continue()
}

func (d *QuantileValueDecoder) Reset() {
	d.quantileDecoder.Reset()
	d.valueDecoder.Reset()
}

func (d *QuantileValueDecoder) Decode(dstPtr *QuantileValue) error {
	val := dstPtr

	var err error

	// Read bits that indicate which fields follow.
	val.modifiedFields.mask = d.buf.ReadBits(d.fieldCount)

	if val.modifiedFields.mask&fieldModifiedQuantileValueQuantile != 0 {
		// Field is changed and is present, decode it.
		err = d.quantileDecoder.Decode(&val.quantile)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedQuantileValueValue != 0 {
		// Field is changed and is present, decode it.
		err = d.valueDecoder.Decode(&val.value)
		if err != nil {
			return err
		}
	}

	return nil
}
