// Code generated by stefgen. DO NOT EDIT.
package oteltef

import (
	"bytes"
	"fmt"
	"math/rand/v2"
	"strings"
	"unsafe"

	"modernc.org/b/v2"

	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/encoders"
	"github.com/splunk/stef/go/pkg/schema"
)

var _ = strings.Compare
var _ = encoders.StringEncoder{}
var _ = schema.WireSchema{}
var _ = bytes.NewBuffer

type Resource struct {
	schemaURL              string
	attributes             Attributes
	droppedAttributesCount uint64

	// modifiedFields keeps track of which fields are modified.
	modifiedFields modifiedFields
}

const ResourceStructName = "Resource"

// Bitmasks for "modified" flags for each field.
const (
	fieldModifiedResourceSchemaURL = uint64(1 << iota)
	fieldModifiedResourceAttributes
	fieldModifiedResourceDroppedAttributesCount
)

// Init must be called once, before the Resource is used.
func (s *Resource) Init() {
	s.init(nil, 0)
}

func NewResource() *Resource {
	var s Resource
	s.init(nil, 0)
	return &s
}

func (s *Resource) init(parentModifiedFields *modifiedFields, parentModifiedBit uint64) {
	s.modifiedFields.parent = parentModifiedFields
	s.modifiedFields.parentBit = parentModifiedBit

	s.attributes.init(&s.modifiedFields, fieldModifiedResourceAttributes)
}

// reset the struct to its initial state, as if init() was just called.
// Will not reset internal fields such as parentModifiedFields.
func (s *Resource) reset() {

	s.attributes.reset()
}

// fixParent sets the parentModifiedFields pointer to the supplied value.
// This is used when the parent is moved in memory for example because the parent
// an array element and the array was expanded.
func (s *Resource) fixParent(parentModifiedFields *modifiedFields) {
	s.modifiedFields.parent = parentModifiedFields

	s.attributes.fixParent(&s.modifiedFields)
}

func (s *Resource) SchemaURL() string {
	return s.schemaURL
}

// SetSchemaURL sets the value of SchemaURL field.
func (s *Resource) SetSchemaURL(v string) {
	if !pkg.StringEqual(s.schemaURL, v) {
		s.schemaURL = v
		s.markSchemaURLModified()
	}
}

func (s *Resource) markSchemaURLModified() {
	s.modifiedFields.markModified(fieldModifiedResourceSchemaURL)
}

// IsSchemaURLModified returns true the value of SchemaURL field was modified since
// Resource was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *Resource) IsSchemaURLModified() bool {
	return s.modifiedFields.mask&fieldModifiedResourceSchemaURL != 0
}

func (s *Resource) Attributes() *Attributes {
	return &s.attributes
}

func (s *Resource) markAttributesModified() {
	s.modifiedFields.markModified(fieldModifiedResourceAttributes)
}

// IsAttributesModified returns true the value of Attributes field was modified since
// Resource was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *Resource) IsAttributesModified() bool {
	return s.modifiedFields.mask&fieldModifiedResourceAttributes != 0
}

func (s *Resource) DroppedAttributesCount() uint64 {
	return s.droppedAttributesCount
}

// SetDroppedAttributesCount sets the value of DroppedAttributesCount field.
func (s *Resource) SetDroppedAttributesCount(v uint64) {
	if !pkg.Uint64Equal(s.droppedAttributesCount, v) {
		s.droppedAttributesCount = v
		s.markDroppedAttributesCountModified()
	}
}

func (s *Resource) markDroppedAttributesCountModified() {
	s.modifiedFields.markModified(fieldModifiedResourceDroppedAttributesCount)
}

// IsDroppedAttributesCountModified returns true the value of DroppedAttributesCount field was modified since
// Resource was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *Resource) IsDroppedAttributesCountModified() bool {
	return s.modifiedFields.mask&fieldModifiedResourceDroppedAttributesCount != 0
}

func (s *Resource) markModifiedRecursively() {

	s.attributes.markModifiedRecursively()

	s.modifiedFields.mask =
		fieldModifiedResourceSchemaURL |
			fieldModifiedResourceAttributes |
			fieldModifiedResourceDroppedAttributesCount | 0
}

func (s *Resource) markUnmodifiedRecursively() {

	if s.IsSchemaURLModified() {
	}

	if s.IsAttributesModified() {
		s.attributes.markUnmodifiedRecursively()
	}

	if s.IsDroppedAttributesCountModified() {
	}

	s.modifiedFields.mask = 0
}

func (s *Resource) Clone() *Resource {
	return &Resource{
		schemaURL:              s.schemaURL,
		attributes:             s.attributes.Clone(),
		droppedAttributesCount: s.droppedAttributesCount,
	}
}

// ByteSize returns approximate memory usage in bytes. Used to calculate
// memory used by dictionaries.
func (s *Resource) byteSize() uint {
	return uint(unsafe.Sizeof(*s)) +
		s.attributes.byteSize() + 0
}

func copyResource(dst *Resource, src *Resource) {
	dst.SetSchemaURL(src.schemaURL)
	copyAttributes(&dst.attributes, &src.attributes)
	dst.SetDroppedAttributesCount(src.droppedAttributesCount)
}

// CopyFrom() performs a deep copy from src.
func (s *Resource) CopyFrom(src *Resource) {
	copyResource(s, src)
}

func (s *Resource) markParentModified() {
	s.modifiedFields.parent.markModified(s.modifiedFields.parentBit)
}

// mutateRandom mutates fields in a random, deterministic manner using
// random parameter as a deterministic generator. Only fields that exist
// in the schem are mutated, allowing to generate data for specified schema.
func (s *Resource) mutateRandom(random *rand.Rand, schem *schema.Schema) {
	// Get the field count for this struct from the schema. If the schema specifies
	// fewer field count than the one we have in this code then we will not mutate
	// fields that are not in the schema.
	fieldCount, err := schem.FieldCount("Resource")
	if err != nil {
		panic(fmt.Sprintf("cannot get field count for %s: %v", "Resource", err))
	}

	const randRange = max(3, 2) // At least 2 to ensure we don't recurse infinitely if there is only 1 field.

	if fieldCount <= 0 {
		return // SchemaURL and all subsequent fields are skipped.
	}
	// Maybe mutate SchemaURL
	if random.IntN(randRange) == 0 {
		s.SetSchemaURL(pkg.StringRandom(random))
	}
	if fieldCount <= 1 {
		return // Attributes and all subsequent fields are skipped.
	}
	// Maybe mutate Attributes
	if random.IntN(randRange) == 0 {
		s.attributes.mutateRandom(random, schem)
	}
	if fieldCount <= 2 {
		return // DroppedAttributesCount and all subsequent fields are skipped.
	}
	// Maybe mutate DroppedAttributesCount
	if random.IntN(randRange) == 0 {
		s.SetDroppedAttributesCount(pkg.Uint64Random(random))
	}
}

// IsEqual performs deep comparison and returns true if struct is equal to right.
func (s *Resource) IsEqual(right *Resource) bool {
	// Compare SchemaURL field.
	if !pkg.StringEqual(s.schemaURL, right.schemaURL) {
		return false
	}
	// Compare Attributes field.
	if !s.attributes.IsEqual(&right.attributes) {
		return false
	}
	// Compare DroppedAttributesCount field.
	if !pkg.Uint64Equal(s.droppedAttributesCount, right.droppedAttributesCount) {
		return false
	}

	return true
}

func ResourceEqual(left, right *Resource) bool {
	return left.IsEqual(right)
}

// CmpResource performs deep comparison and returns an integer that
// will be 0 if left == right, negative if left < right, positive if left > right.
func CmpResource(left, right *Resource) int {
	if left == nil {
		if right == nil {
			return 0
		}
		return -1
	}
	if right == nil {
		return 1
	}

	// Compare SchemaURL field.
	if c := strings.Compare(left.schemaURL, right.schemaURL); c != 0 {
		return c
	}

	// Compare Attributes field.
	if c := CmpAttributes(&left.attributes, &right.attributes); c != 0 {
		return c
	}

	// Compare DroppedAttributesCount field.
	if c := pkg.Uint64Compare(left.droppedAttributesCount, right.droppedAttributesCount); c != 0 {
		return c
	}

	return 0
}

// ResourceEncoder implements encoding of Resource
type ResourceEncoder struct {
	buf     pkg.BitsWriter
	limiter *pkg.SizeLimiter

	// forceModifiedFields is set to true if the next encoding operation
	// must write all fields, whether they are modified or no.
	// This is used after frame restarts so that the data can be decoded
	// from the frame start.
	forceModifiedFields bool

	schemaURLEncoder encoders.StringEncoder

	attributesEncoder     *AttributesEncoder
	isAttributesRecursive bool // Indicates Attributes field's type is recursive.

	droppedAttributesCountEncoder encoders.Uint64Encoder

	dict *ResourceEncoderDict

	keepFieldMask uint64
	fieldCount    uint
}

type ResourceEntry struct {
	refNum uint64
	val    *Resource
}

// ResourceEncoderDict is the dictionary used by ResourceEncoder
type ResourceEncoderDict struct {
	dict    b.Tree[*Resource, ResourceEntry]
	limiter *pkg.SizeLimiter
}

func (d *ResourceEncoderDict) Init(limiter *pkg.SizeLimiter) {
	d.dict = *b.TreeNew[*Resource, ResourceEntry](CmpResource)
	d.dict.Set(nil, ResourceEntry{}) // nil Resource is RefNum 0
	d.limiter = limiter
}

func (d *ResourceEncoderDict) Reset() {
	d.dict.Clear()
	d.dict.Set(nil, ResourceEntry{}) // nil Resource is RefNum 0
}

func (e *ResourceEncoder) Init(state *WriterState, columns *pkg.WriteColumnSet) error {
	// Remember this encoder in the state so that we can detect recursion.
	if state.ResourceEncoder != nil {
		panic("cannot initialize ResourceEncoder: already initialized")
	}
	state.ResourceEncoder = e
	defer func() { state.ResourceEncoder = nil }()

	e.limiter = &state.limiter
	e.dict = &state.Resource

	// Number of fields in the output data schema.
	var err error
	e.fieldCount, err = state.StructFieldCounts.ResourceFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %v", "Resource", err)
	}
	// Set that many 1 bits in the keepFieldMask. All fields with higher number
	// will be skipped when encoding.
	e.keepFieldMask = ^(^uint64(0) << e.fieldCount)

	// Init encoder for SchemaURL field.
	if e.fieldCount <= 0 {
		return nil // SchemaURL and all subsequent fields are skipped.
	}
	err = e.schemaURLEncoder.Init(&state.SchemaURL, e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	// Init encoder for Attributes field.
	if e.fieldCount <= 1 {
		return nil // Attributes and all subsequent fields are skipped.
	}
	if state.AttributesEncoder != nil {
		// Recursion detected, use the existing encoder.
		e.attributesEncoder = state.AttributesEncoder
		e.isAttributesRecursive = true
	} else {
		e.attributesEncoder = new(AttributesEncoder)
		err = e.attributesEncoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}

	// Init encoder for DroppedAttributesCount field.
	if e.fieldCount <= 2 {
		return nil // DroppedAttributesCount and all subsequent fields are skipped.
	}
	err = e.droppedAttributesCountEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

func (e *ResourceEncoder) Reset() {
	// Since we are resetting the state of encoder make sure the next Encode()
	// call forcedly writes all fields and does not attempt to skip.
	e.forceModifiedFields = true

	if e.fieldCount <= 0 {
		return // SchemaURL and all subsequent fields are skipped.
	}
	e.schemaURLEncoder.Reset()
	if e.fieldCount <= 1 {
		return // Attributes and all subsequent fields are skipped.
	}

	if !e.isAttributesRecursive {
		e.attributesEncoder.Reset()
	}

	if e.fieldCount <= 2 {
		return // DroppedAttributesCount and all subsequent fields are skipped.
	}
	e.droppedAttributesCountEncoder.Reset()
}

// Encode encodes val into buf
func (e *ResourceEncoder) Encode(val *Resource) {
	var bitCount uint

	// Check if the Resource exists in the dictionary.
	entry, exists := e.dict.dict.Get(val)
	if exists {
		// The Resource exists, we will reference it.
		// Indicate a RefNum follows.
		e.buf.WriteBit(0)
		// Encode refNum.
		bitCount = e.buf.WriteUvarintCompact(entry.refNum)

		// Account written bits in the limiter.
		e.limiter.AddFrameBits(1 + bitCount)

		// Mark all fields non-modified recursively so that next Encode() correctly
		// encodes only fields that change after this.
		val.markUnmodifiedRecursively()
		return
	}

	// The Resource does not exist in the dictionary. Add it to the dictionary.
	valInDict := val.Clone()
	entry = ResourceEntry{refNum: uint64(e.dict.dict.Len()), val: valInDict}
	e.dict.dict.Set(valInDict, entry)
	e.dict.limiter.AddDictElemSize(valInDict.byteSize())

	// Indicate that an encoded Resource follows.
	e.buf.WriteBit(1)
	bitCount += 1
	// TODO: optimize and merge WriteBit with the following WriteBits.
	// Mask that describes what fields are encoded. Start with all modified fields.
	fieldMask := val.modifiedFields.mask

	// If forceModifiedFields we need to set to 1 all bits so that we
	// force writing of all fields.
	if e.forceModifiedFields {
		fieldMask =
			fieldModifiedResourceSchemaURL |
				fieldModifiedResourceAttributes |
				fieldModifiedResourceDroppedAttributesCount | 0
	}

	// Only write fields that we want to write. See Init() for keepFieldMask.
	fieldMask &= e.keepFieldMask

	// Write bits to indicate which fields follow.
	e.buf.WriteBits(fieldMask, e.fieldCount)
	bitCount += e.fieldCount

	// Encode modified, present fields.

	if fieldMask&fieldModifiedResourceSchemaURL != 0 {
		// Encode SchemaURL
		e.schemaURLEncoder.Encode(val.schemaURL)
	}

	if fieldMask&fieldModifiedResourceAttributes != 0 {
		// Encode Attributes
		e.attributesEncoder.Encode(&val.attributes)
	}

	if fieldMask&fieldModifiedResourceDroppedAttributesCount != 0 {
		// Encode DroppedAttributesCount
		e.droppedAttributesCountEncoder.Encode(val.droppedAttributesCount)
	}

	// Account written bits in the limiter.
	e.limiter.AddFrameBits(bitCount)

	// Mark all fields non-modified so that next Encode() correctly
	// encodes only fields that change after this.
	val.modifiedFields.mask = 0
}

// CollectColumns collects all buffers from all encoders into buf.
func (e *ResourceEncoder) CollectColumns(columnSet *pkg.WriteColumnSet) {
	columnSet.SetBits(&e.buf)
	colIdx := 0

	// Collect SchemaURL field.
	if e.fieldCount <= 0 {
		return // SchemaURL and subsequent fields are skipped.
	}

	e.schemaURLEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++

	// Collect Attributes field.
	if e.fieldCount <= 1 {
		return // Attributes and subsequent fields are skipped.
	}
	if !e.isAttributesRecursive {
		e.attributesEncoder.CollectColumns(columnSet.At(colIdx))
		colIdx++
	}

	// Collect DroppedAttributesCount field.
	if e.fieldCount <= 2 {
		return // DroppedAttributesCount and subsequent fields are skipped.
	}

	e.droppedAttributesCountEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++
}

// ResourceDecoder implements decoding of Resource
type ResourceDecoder struct {
	buf        pkg.BitsReader
	column     *pkg.ReadableColumn
	fieldCount uint

	schemaURLDecoder encoders.StringDecoder

	attributesDecoder     *AttributesDecoder
	isAttributesRecursive bool

	droppedAttributesCountDecoder encoders.Uint64Decoder

	dict *ResourceDecoderDict
}

// Init is called once in the lifetime of the stream.
func (d *ResourceDecoder) Init(state *ReaderState, columns *pkg.ReadColumnSet) error {
	// Remember this decoder in the state so that we can detect recursion.
	if state.ResourceDecoder != nil {
		panic("cannot initialize ResourceDecoder: already initialized")
	}
	state.ResourceDecoder = d
	defer func() { state.ResourceDecoder = nil }()

	// Number of fields in the input data schema.
	var err error
	d.fieldCount, err = state.StructFieldCounts.ResourceFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %v", "Resource", err)
	}

	d.column = columns.Column()
	d.dict = &state.Resource

	if d.fieldCount <= 0 {
		return nil // SchemaURL and subsequent fields are skipped.
	}
	err = d.schemaURLDecoder.Init(&state.SchemaURL, columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 1 {
		return nil // Attributes and subsequent fields are skipped.
	}
	if state.AttributesDecoder != nil {
		// Recursion detected, use the existing decoder.
		d.attributesDecoder = state.AttributesDecoder
		d.isAttributesRecursive = true // Mark that we are using a recursive decoder.
	} else {
		d.attributesDecoder = new(AttributesDecoder)
		err = d.attributesDecoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}
	if d.fieldCount <= 2 {
		return nil // DroppedAttributesCount and subsequent fields are skipped.
	}
	err = d.droppedAttributesCountDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

// Continue is called at the start of the frame to continue decoding column data.
// This should set the decoder's source buffer, so the new decoding continues from
// the supplied column data. This should NOT reset the internal state of the decoder,
// since columns can cross frame boundaries and the new column data is considered
// continuation of that same column in the previous frame.
func (d *ResourceDecoder) Continue() {
	d.buf.Reset(d.column.Data())

	if d.fieldCount <= 0 {
		return // SchemaURL and subsequent fields are skipped.
	}
	d.schemaURLDecoder.Continue()
	if d.fieldCount <= 1 {
		return // Attributes and subsequent fields are skipped.
	}

	if !d.isAttributesRecursive {
		d.attributesDecoder.Continue()
	}

	if d.fieldCount <= 2 {
		return // DroppedAttributesCount and subsequent fields are skipped.
	}
	d.droppedAttributesCountDecoder.Continue()
}

func (d *ResourceDecoder) Reset() {

	if d.fieldCount <= 0 {
		return // SchemaURL and all subsequent fields are skipped.
	}
	d.schemaURLDecoder.Reset()
	if d.fieldCount <= 1 {
		return // Attributes and all subsequent fields are skipped.
	}

	if !d.isAttributesRecursive {
		d.attributesDecoder.Reset()
	}

	if d.fieldCount <= 2 {
		return // DroppedAttributesCount and all subsequent fields are skipped.
	}
	d.droppedAttributesCountDecoder.Reset()
}

func (d *ResourceDecoder) Decode(dstPtr **Resource) error {
	// Check if this is a dictionary-based decoding.
	dictFlag := d.buf.ReadBit()
	if dictFlag == 0 {
		refNum := d.buf.ReadUvarintCompact()
		if refNum >= uint64(len(d.dict.dict)) {
			return pkg.ErrInvalidRefNum
		}
		*dstPtr = d.dict.dict[refNum]
		return nil
	}

	// *dstPtr is pointing to a element in the dictionary. We are not allowed
	// to modify it. Make a clone of it and decode into the clone.
	val := (*dstPtr).Clone()
	*dstPtr = val

	var err error

	// Read bits that indicate which fields follow.
	val.modifiedFields.mask = d.buf.ReadBits(d.fieldCount)

	if val.modifiedFields.mask&fieldModifiedResourceSchemaURL != 0 {
		// Field is changed and is present, decode it.
		err = d.schemaURLDecoder.Decode(&val.schemaURL)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedResourceAttributes != 0 {
		// Field is changed and is present, decode it.
		err = d.attributesDecoder.Decode(&val.attributes)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedResourceDroppedAttributesCount != 0 {
		// Field is changed and is present, decode it.
		err = d.droppedAttributesCountDecoder.Decode(&val.droppedAttributesCount)
		if err != nil {
			return err
		}
	}

	d.dict.dict = append(d.dict.dict, val)

	return nil
}

// ResourceDecoderDict is the dictionary used by ResourceDecoder
type ResourceDecoderDict struct {
	dict []*Resource
}

func (d *ResourceDecoderDict) Init() {
	d.dict = d.dict[:0]
	d.dict = append(d.dict, nil) // nil Resource is RefNum 0
}

// Reset the dictionary to initial state. Used when a frame is
// started with RestartDictionaries flag.
func (d *ResourceDecoderDict) Reset() {
	d.Init()
}
