// Code generated by stefc. DO NOT EDIT.
package ints

import (
	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/encoders"
)

var _ = (*encoders.StringEncoder)(nil)

type WriterState struct {
	limiter pkg.SizeLimiter

	StructFieldCounts StructFieldCounts

	// Dictionaries

	// Encoders that are being Init-ed, to detect recursion.
	RecordEncoder *RecordEncoder

	Allocators Allocators
}

func (d *WriterState) Init(opts *pkg.WriterOptions) {
	d.limiter.Init(opts)

	d.StructFieldCounts.Init(opts.Schema)

	// Init dictionaries

}

func (d *WriterState) ResetDicts() {
	d.limiter.ResetDict()
}
