// Code generated by stefc. DO NOT EDIT.
package otelstef

type SeverityNumber uint64

const (
	SeverityNumberUnspecified SeverityNumber = 0
	SeverityNumberTrace       SeverityNumber = 1
	SeverityNumberTrace2      SeverityNumber = 2
	SeverityNumberTrace3      SeverityNumber = 3
	SeverityNumberTrace4      SeverityNumber = 4
	SeverityNumberDebug       SeverityNumber = 5
	SeverityNumberDebug2      SeverityNumber = 6
	SeverityNumberDebug3      SeverityNumber = 7
	SeverityNumberDebug4      SeverityNumber = 8
	SeverityNumberInfo        SeverityNumber = 9
	SeverityNumberInfo2       SeverityNumber = 10
	SeverityNumberInfo3       SeverityNumber = 11
	SeverityNumberInfo4       SeverityNumber = 12
	SeverityNumberWarn        SeverityNumber = 13
	SeverityNumberWarn2       SeverityNumber = 14
	SeverityNumberWarn3       SeverityNumber = 15
	SeverityNumberWarn4       SeverityNumber = 16
	SeverityNumberError       SeverityNumber = 17
	SeverityNumberError2      SeverityNumber = 18
	SeverityNumberError3      SeverityNumber = 19
	SeverityNumberError4      SeverityNumber = 20
	SeverityNumberFatal       SeverityNumber = 21
	SeverityNumberFatal2      SeverityNumber = 22
	SeverityNumberFatal3      SeverityNumber = 23
	SeverityNumberFatal4      SeverityNumber = 24
)
