; Validated by https://author-tools.ietf.org/abnf

schema = MAYBELWSP 1*(struct / oneof / multimap) MAYBELWSP

; struct rules

struct = "struct" WSP struct-name ; WSP *struct-modifier LWSP "{" LWSP struct-body LWSP "}"

struct-name = identifier

identifier = ALPHA *(ALPHA / DIGIT)

struct-modifier = dict-modifier / "main"

dict-modifier = "dict(" identifier ")"

struct-body = 1*(struct-field LWSP)

struct-field = identifier WSP field-type [WSP struct-field-modifier]

struct-field-modifier = dict-modifier / optional-modifier

optional-modifier = "optional"

; oneof rules

oneof = "oneof" WSP oneof-name WSP "{" LWSP oneof-body LWSP "}"

oneof-name = identifier

oneof-body = 1*(oneof-field LWSP)

oneof-field = identifier WSP field-type [WSP oneof-field-modifier]

oneof-field-modifier = dict-modifier

; multimap rules

multimap = "multimap" WSP multimap-name WSP "{" LWSP multimap-body LWSP "}"

multimap-name = identifier

multimap-body = multimap-key LWSP multimap-value

multimap-key = "Key" WSP field-type [WSP multimap-field-modifier]

multimap-value = "Value" WSP field-type [WSP multimap-field-modifier]

multimap-field-modifier = dict-modifier

; type definition

field-type = [array-specifier] builtin-type / userdefined-type

array-specifier = "[]"

builtin-type = "bool" / "int64" / "float64" / "string" / "bytes"

userdefined-type = identifier

MAYBELWSP = *(CR / LF / SP / HTAB)
