// Code generated by stefgen. DO NOT EDIT.
package com.example.oteltef;

import net.stef.BytesWriter;
import net.stef.SizeLimiter;
import net.stef.WriteColumnSet;
import net.stef.codecs.*;

import java.io.IOException;

// Encoder for EnvelopeAttributes
public class EnvelopeAttributesEncoder {
    private BytesWriter buf;
    private WriteColumnSet columns;
    private SizeLimiter limiter;

    private StringEncoder keyEncoder;
    private BytesEncoder valueEncoder;

    private EnvelopeAttributes lastVal = new EnvelopeAttributes();

    public void init(WriterState state, WriteColumnSet columns) throws IOException {
        this.limiter = state.getLimiter();
        keyEncoder = new StringEncoder();
        keyEncoder.init(null, limiter, columns.addSubColumn());
        valueEncoder = new BytesEncoder();
        valueEncoder.init(null, limiter, columns.addSubColumn());
    }

    public void reset() {
    
        keyEncoder.reset();
    
        valueEncoder.reset();
    }

    // IsEqual performs deep comparison and returns true if encoder's previously encoded value is equal to list.
    public boolean isEqual(EnvelopeAttributes list) {
        return lastVal.isEqual(list);
    }

    public boolean encode(EnvelopeAttributes list) {
        // Implement encoding logic as in Go template
        return false;
    }

    private boolean encodeValuesOnly(EnvelopeAttributes list) {
        // Implement value-only encoding logic
        return false;
    }

    private void encodeFull(EnvelopeAttributes list) {
        // Implement full encoding logic
    }

    public void rencodeLast() {
        // Implement re-encoding of last value
    }

    public void collectColumns(WriteColumnSet columnSet) {
        // Implement column collection logic
    }
}

