// Code generated by stefgen. DO NOT EDIT.
// Exemplar Java class generated from template
package com.example.oteltef;

import net.stef.StringValue;
import net.stef.Types;
import java.util.*;

public class Exemplar {
    
    long timestamp;
    ExemplarValue value;
    Types.Bytes spanID;
    Types.Bytes traceID;
    Attributes filteredAttributes;

    // modifiedFields keeps track of which fields are modified.
    private ModifiedFields modifiedFields = new ModifiedFields();
    ModifiedFields getModifiedFields() { return this.modifiedFields; }

    public static final String ExemplarStructName = "Exemplar";

    // Bitmasks for "modified" flags for each field.
    
    public static final long fieldModifiedTimestamp = 1 << 0;
    public static final long fieldModifiedValue = 1 << 1;
    public static final long fieldModifiedSpanID = 1 << 2;
    public static final long fieldModifiedTraceID = 1 << 3;
    public static final long fieldModifiedFilteredAttributes = 1 << 4;

    

    // Init must be called once, before the Exemplar is used.
    public void init() {
        this.init(null, 0);
    }

    public static Exemplar newExemplar() {
        Exemplar s = new Exemplar();
        s.init(null, 0);
        return s;
    }

    void init(ModifiedFields parentModifiedFields, long parentModifiedBit) {
        this.modifiedFields.parent = parentModifiedFields;
        this.modifiedFields.parentBit = parentModifiedBit;
        
        this.value.init(this.modifiedFields, fieldModifiedValue);
        this.filteredAttributes.init(this.modifiedFields, fieldModifiedFilteredAttributes);
    }

    
    public long getTimestamp() {
        return this.timestamp;
    }

    
    // setTimestamp sets the value of Timestamp field.
    public void setTimestamp(long v) {
        if (!Types.Uint64Equal(this.timestamp, v)) {
            this.timestamp = v;
            this.markTimestampModified();
        }
    }

    

    private void markTimestampModified() {
        this.modifiedFields.markModified(fieldModifiedTimestamp);
    }
    

    // isTimestampModified returns true if the value of Timestamp field was modified since
    // Exemplar was created, encoded or decoded. If the field is modified
    // it will be encoded by the next Write() operation. If the field is decoded by the
    // next Read() operation the modified flag will be set.
    public boolean isTimestampModified() {
        return (this.modifiedFields.mask & fieldModifiedTimestamp) != 0;
    }
    
    public ExemplarValue getValue() {
        return this.value;
    }

    

    // isValueModified returns true if the value of Value field was modified since
    // Exemplar was created, encoded or decoded. If the field is modified
    // it will be encoded by the next Write() operation. If the field is decoded by the
    // next Read() operation the modified flag will be set.
    public boolean isValueModified() {
        return (this.modifiedFields.mask & fieldModifiedValue) != 0;
    }
    
    public Types.Bytes getSpanID() {
        return this.spanID;
    }

    
    // setSpanID sets the value of SpanID field.
    public void setSpanID(Types.Bytes v) {
        if (!Types.BytesEqual(this.spanID, v)) {
            this.spanID = v;
            this.markSpanIDModified();
        }
    }

    

    private void markSpanIDModified() {
        this.modifiedFields.markModified(fieldModifiedSpanID);
    }
    

    // isSpanIDModified returns true if the value of SpanID field was modified since
    // Exemplar was created, encoded or decoded. If the field is modified
    // it will be encoded by the next Write() operation. If the field is decoded by the
    // next Read() operation the modified flag will be set.
    public boolean isSpanIDModified() {
        return (this.modifiedFields.mask & fieldModifiedSpanID) != 0;
    }
    
    public Types.Bytes getTraceID() {
        return this.traceID;
    }

    
    // setTraceID sets the value of TraceID field.
    public void setTraceID(Types.Bytes v) {
        if (!Types.BytesEqual(this.traceID, v)) {
            this.traceID = v;
            this.markTraceIDModified();
        }
    }

    

    private void markTraceIDModified() {
        this.modifiedFields.markModified(fieldModifiedTraceID);
    }
    

    // isTraceIDModified returns true if the value of TraceID field was modified since
    // Exemplar was created, encoded or decoded. If the field is modified
    // it will be encoded by the next Write() operation. If the field is decoded by the
    // next Read() operation the modified flag will be set.
    public boolean isTraceIDModified() {
        return (this.modifiedFields.mask & fieldModifiedTraceID) != 0;
    }
    
    public Attributes getFilteredAttributes() {
        return this.filteredAttributes;
    }

    

    // isFilteredAttributesModified returns true if the value of FilteredAttributes field was modified since
    // Exemplar was created, encoded or decoded. If the field is modified
    // it will be encoded by the next Write() operation. If the field is decoded by the
    // next Read() operation the modified flag will be set.
    public boolean isFilteredAttributesModified() {
        return (this.modifiedFields.mask & fieldModifiedFilteredAttributes) != 0;
    }
    

    public void markUnmodifiedRecursively() {
        
        if (this.isTimestampModified()) {
        }
        
        if (this.isValueModified()) {
            this.value.markUnmodifiedRecursively();
        }
        
        if (this.isSpanIDModified()) {
        }
        
        if (this.isTraceIDModified()) {
        }
        
        if (this.isFilteredAttributesModified()) {
            this.filteredAttributes.markUnmodifiedRecursively();
        }
        
        this.modifiedFields.mask = 0;
    }

    public Exemplar clone() {
        Exemplar cpy = new Exemplar();
        cpy.timestamp = this.timestamp;
        cpy.value = this.value.clone();
        cpy.spanID = this.spanID;
        cpy.traceID = this.traceID;
        cpy.filteredAttributes = this.filteredAttributes.clone();
        return cpy;
    }

    // isEqual performs deep comparison and returns true if struct is equal to val.
    public boolean isEqual(Exemplar val) {
        if (!Types.Uint64Equal(this.timestamp, val.timestamp)) {
            return false;
        }
        if (!this.value.isEqual(val.value)) {
            return false;
        }
        if (!Types.BytesEqual(this.spanID, val.spanID)) {
            return false;
        }
        if (!Types.BytesEqual(this.traceID, val.traceID)) {
            return false;
        }
        if (!this.filteredAttributes.isEqual(val.filteredAttributes)) {
            return false;
        }
        return true;
    }

    public static boolean ExemplarEqual(Exemplar left, Exemplar right) {
        return left.isEqual(right);
    }

    // cmpExemplar performs deep comparison and returns an integer that
    // will be 0 if left == right, negative if left < right, positive if left > right.
    public static int compare(Exemplar left, Exemplar right) {
        if (left == null) {
            if (right == null) {
                return 0;
            }
            return -1;
        }
        if (right == null) {
            return 1;
        }
        int c;
        
        c = Types.Uint64Compare(left.timestamp, right.timestamp);
        if (c != 0) {
            return c;
        }
        
        c = ExemplarValue.compare(left.value, right.value);
        if (c != 0) {
            return c;
        }
        
        c = Types.BytesCompare(left.spanID, right.spanID);
        if (c != 0) {
            return c;
        }
        
        c = Types.BytesCompare(left.traceID, right.traceID);
        if (c != 0) {
            return c;
        }
        
        c = CmpAttributes(left.filteredAttributes, right.filteredAttributes);
        if (c != 0) {
            return c;
        }
        
        return 0;
    }

    public void mutateRandom(Random random) {
        final int fieldCount = 5;
        
        if (random.nextInt(fieldCount) == 0) {
            this.setTimestamp(Types.Uint64Random(random));
        }
        
        if (random.nextInt(fieldCount) == 0) {
            this.value.mutateRandom(random);
        }
        
        if (random.nextInt(fieldCount) == 0) {
            this.setSpanID(Types.BytesRandom(random));
        }
        
        if (random.nextInt(fieldCount) == 0) {
            this.setTraceID(Types.BytesRandom(random));
        }
        
        if (random.nextInt(fieldCount) == 0) {
            this.filteredAttributes.mutateRandom(random);
        }
        
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        return isEqual((Exemplar)o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            timestamp,
            value,
            spanID,
            traceID,
            filteredAttributes
        );
    }
}
