// Code generated by stefgen. DO NOT EDIT.
package com.example.oteltef;

import net.stef.Types;

import java.util.*;
import java.util.Objects;

// ExemplarArray is a variable size array.
public class ExemplarArray {
    Exemplar[] elems = new Exemplar[0];
    int size = 0;

    private ModifiedFields parentModifiedFields;
    private long parentModifiedBit;

    public void init(ModifiedFields parentModifiedFields, long parentModifiedBit) {
        this.parentModifiedFields = parentModifiedFields;
        this.parentModifiedBit = parentModifiedBit;
    }

    // Clone() creates a deep copy of ExemplarArray
    public ExemplarArray clone() {
        ExemplarArray clone = new ExemplarArray();
        copyExemplarArray(clone, this);
        return clone;
    }

    // ByteSize returns approximate memory usage in bytes. Used to calculate
    // memory used by dictionaries.
    public int byteSize() {
        int size = 0; // calculate size of the array in bytes.
        
        for (var elem : elems) {
            size += elem.byteSize();
        }
        
        return size;
    }

    

    // Append a new element at the end of the array.
    public void append(Exemplar val) {
        ensureElemsSize(size + 1);
        elems[size] = val;
        size++;
        markModified();
    }

    void ensureElemsSize(int newSize) {
        if (elems.length < newSize) {
            newSize = Math.max(newSize, elems.length * 2);
            Exemplar[] newElems = new Exemplar[newSize];
            System.arraycopy(elems, 0, newElems, 0, elems.length);
        }
        size = newSize;
    }

    public void markModified() {
        if (parentModifiedFields != null) {
            parentModifiedFields.markModified(parentModifiedBit);
        }
    }

    public void markUnmodified() {
        if (parentModifiedFields != null) {
            parentModifiedFields.markUnmodified();
        }
    }

    public void markUnmodifiedRecursively() {
        
        for (var elem : elems) {
            elem.markUnmodifiedRecursively();
        }
        
    }

    public static void copyExemplarArray(ExemplarArray dst, ExemplarArray src) {
        if dst.elems.length!=src.elems.length {
            dst.elems = ensureElemsSize(dst.elems, src.elems.length)
            dst.markModified()
        }
        if src.elems.length>0 {
            // Allocate all elements at once.
            elems := make([]Exemplar, src.elems.length)
            for i := range src.elems {
                // Init the element.
                elems[i].init(dst.parentModifiedFields, dst.parentModifiedBit)
                // Point to allocated element.
                dst.elems[i] = &elems[i]
                // Copy the element.
                copyExemplar(dst.elems[i], src.elems[i])
            }
        }
    }

    // Len returns the number of elements in the array.
    public int len() {
        return size;
    }

    // At returns element at index i.
    public Exemplar at(int i) {
        return elems[i];
    }

    // EnsureLen ensures the length of the array is equal to newLen.
    // It will grow or shrink the array if needed.
    public void ensureLen(int newLen) {
        int oldLen = size;
        if (newLen > oldLen) {
            ensureElemsSize(newLen);
            markModified();
            
            // Initialize newlly added elements.
            for (int i = oldLen; i < newLen; i++) {
                Exemplar elem = new Exemplar();
                elem.init(parentModifiedFields, parentModifiedBit);
                elems[size++] = elem;
            }
            
        } else if (oldLen > newLen) {
            // Shrink it
            size = newLen;
            markModified();
        }
    }

    // IsEqual performs deep comparison and returns true if array is equal to val.
    public boolean isEqual(ExemplarArray val) {
        if (size != val.size) {
            return false;
        }
        for (int i = 0; i < size; i++) {
            
            if (!elems[i].isEqual(val.elems[i])) {
                return false;
            }
            
        }
        return true;
    }

    // compare performs deep comparison and returns an integer that
    // will be 0 if left == right, negative if left < right, positive if left > right.
    public static int compare(ExemplarArray left, ExemplarArray right) {
        int c = left.size - right.size;
        if (c != 0) {
            return c;
        }
        for (int i = 0; i < left.size; i++) {
            int fc = Exemplar.compare(left.elems[i], right.elems[i]);
            if (fc < 0) {
                return -1;
            }
            if (fc > 0) {
                return 1;
            }
        }
        return 0;
    }

    // mutateRandom mutates fields in a random, deterministic manner using
    // random parameter as a deterministic generator.
    public void mutateRandom(Random random) {
        if (random.nextInt(20) == 0) {
            ensureLen(len() + 1);
        }
        if (random.nextInt(20) == 0 && len() > 0) {
            ensureLen(len() - 1);
        }
        for (int i = 0; i < size; i++) {
            if (random.nextInt(2 * size) == 0) {
                
                elems[i].mutateRandom(random);
                
            }
        }
    }
}
