// Code generated by stefgen. DO NOT EDIT.
// ExemplarValueDecoder implements decoding of ExemplarValue
package com.example.oteltef;

import net.stef.BitsReader;
import net.stef.ReadColumnSet;
import net.stef.ReadableColumn;
import net.stef.codecs.*;

public class ExemplarValueDecoder {
    private final BitsReader buf = new BitsReader();
    private ReadableColumn column;
    private ExemplarValue lastValPtr;
    private ExemplarValue lastVal = new ExemplarValue();
    private int fieldCount;

    
    private Int64Decoder int64Decoder = new Int64Decoder();
    private Float64Decoder float64Decoder = new Float64Decoder();
    

    // Init is called once in the lifetime of the stream.
    public void init(ReaderState state, ReadColumnSet columns) throws Exception {
        state.setExemplarValueDecoder(this);
        if (state.getOverrideSchema() != null) {
            int fieldCount = state.getOverrideSchema().fieldCount("ExemplarValue");
            this.fieldCount = fieldCount;
        } else {
            this.fieldCount = 2;
        }
        this.column = columns.getColumn();
        this.lastVal.init(null, 0);
        this.lastValPtr = this.lastVal;
        Exception err = null;
        
        if (this.fieldCount <= 0) {
            return; // Int64 and subsequent fields are skipped.
        }
            this.int64Decoder.init(columns.addSubColumn());
        if (this.fieldCount <= 1) {
            return; // Float64 and subsequent fields are skipped.
        }
            this.float64Decoder.init(columns.addSubColumn());
    }
}

