// Code generated by stefgen. DO NOT EDIT.
// ExpHistogramBucketsDecoder implements decoding of ExpHistogramBuckets
package com.example.oteltef;

import net.stef.BitsReader;
import net.stef.ReadColumnSet;
import net.stef.ReadableColumn;
import net.stef.codecs.*;

import java.io.IOException;

class ExpHistogramBucketsDecoder {
    private final BitsReader buf = new BitsReader();
    private ReadableColumn column;
    private ExpHistogramBuckets lastVal;
    private int fieldCount;

    
    private Int64Decoder offsetDecoder = new Int64Decoder();
    private Uint64ArrayDecoder bucketCountsDecoder = new Uint64ArrayDecoder();
    

    // Init is called once in the lifetime of the stream.
    public void init(ReaderState state, ReadColumnSet columns) throws IOException {
        state.ExpHistogramBucketsDecoder = this;
        if (state.getOverrideSchema() != null) {
            int fieldCount = state.getOverrideSchema().getFieldCount("ExpHistogramBuckets");
            fieldCount = fieldCount;
        } else {
            fieldCount = 2;
        }
        column = columns.getColumn();
        
        lastVal = new ExpHistogramBuckets(null, 0);
        
        if (this.fieldCount <= 0) {
            return; // Offset and subsequent fields are skipped.
        }
        offsetDecoder.init(columns.addSubColumn());
        if (this.fieldCount <= 1) {
            return; // BucketCounts and subsequent fields are skipped.
        }
        bucketCountsDecoder.init(state, columns.addSubColumn());
    }

    // continueDecoding is called at the start of the frame to continue decoding column data.
    // This should set the decoder's source buffer, so the new decoding continues from
    // the supplied column data. This should NOT reset the internal state of the decoder,
    // since columns can cross frame boundaries and the new column data is considered
    // continuation of that same column in the previous frame.
    public void continueDecoding() {
        this.buf.reset(this.column.getData());
        
        if (this.fieldCount <= 0) {
            return; // Offset and subsequent fields are skipped.
        }
        this.offsetDecoder.continueDecoding();
        if (this.fieldCount <= 1) {
            return; // BucketCounts and subsequent fields are skipped.
        }
        this.bucketCountsDecoder.continueDecoding();
    }

    public void reset() {
        this.offsetDecoder.reset();
        this.bucketCountsDecoder.reset();
    }

    public ExpHistogramBuckets decode(ExpHistogramBuckets dstPtr) throws IOException {
        ExpHistogramBuckets val = dstPtr;
        // Read bits that indicate which fields follow.
        val.modifiedFields.mask = buf.readBits(fieldCount);
        
        
        if ((val.modifiedFields.mask & ExpHistogramBuckets.fieldModifiedOffset) != 0) {
            // Field is changed and is present, decode it.
            val.offset = offsetDecoder.decode();
        }
        
        if ((val.modifiedFields.mask & ExpHistogramBuckets.fieldModifiedBucketCounts) != 0) {
            // Field is changed and is present, decode it.
            val.bucketCounts = bucketCountsDecoder.decode(val.bucketCounts);
        }
        
        
        return val;
    }
}

