// Code generated by stefgen. DO NOT EDIT.
// HistogramValueDecoderDict is the dictionary used by HistogramValueDecoder
package com.example.oteltef;

import java.util.*;

public class HistogramValueDecoderDict {
    private List<HistogramValue> dict = new ArrayList<>();

    public void init() {
        this.dict.clear();
        this.dict.add(null); // null HistogramValue is RefNum 0
    }

    // Reset the dictionary to initial state. Used when a frame is
    // started with RestartDictionaries flag.
    public void reset() {
        this.init();
    }

    public HistogramValue getByIndex(int index) {
        return this.dict.get(index);
    }

    public void add(HistogramValue val) {
        this.dict.add(val);
    }

    public int size() {
        return this.dict.size();
    }
}

