// Code generated by stefgen. DO NOT EDIT.
package com.example.oteltef;

import net.stef.StringValue;
import net.stef.Types;

import java.util.*;
import java.util.Objects;

// KeyValueList is a multimap, (aka an associative array or a list) of key value
// pairs from StringValue to AnyValue.
public class KeyValueList {
    public static class Elem {
        StringValue key;
        AnyValue value;
    }

    Elem[] elems = new Elem[0];

    // elemsLen is the number of elements contains in the elems, elemsLen<=elems.length.
    int elemsLen = 0;

    private int initedCount = 0;
    private ModifiedFields parentModifiedFields;
    private long parentModifiedBit;

    KeyValueList() {
        init(null, 0);
    }

    KeyValueList(ModifiedFields parentModifiedFields, long parentModifiedBit) {
        init(parentModifiedFields, parentModifiedBit);
    }

    private void init(ModifiedFields parentModifiedFields, long parentModifiedBit) {
        this.parentModifiedFields = parentModifiedFields;
        this.parentModifiedBit = parentModifiedBit;
    }

    // Clone() creates a deep copy of KeyValueList
    public KeyValueList clone() {
        KeyValueList clone = new KeyValueList();
        copyKeyValueList(clone, this);
        return clone;
    }

    // Len returns the number of elements in the multimap.
    public int len() {
        return elemsLen;
    }

    // At returns element at index i.
    public Elem at(int i) {
        return elems[i];
    }

    // ensureElems ensures that elems array has at least newLen elements allocated.
    // It will grow/reallocate the array if needed.
    // elemsLen will be set to newLen.
    // This method does not call init() on new elements in the array.
    void ensureElems(int newLen) {
        if (elems.length < newLen) {
            int allocLen = Math.max(newLen, elems.length * 2);
            Elem[] newElems = new Elem[allocLen];
            System.arraycopy(elems, 0, newElems, 0, elems.length);
            elems = newElems;
        }
        elemsLen = newLen;
    }

    // ensureLen ensures the length of the array is equal to newLen.
    // It will grow or shrink the array if needed, and initialize newly added elements
    // if the element type requires initialization.
    public void ensureLen(int newLen) {
        int oldLen = elemsLen;
        if (newLen==oldLen) {
            return; // No change needed.
        }

        ensureElems(newLen);
        for (int i=initedCount; i < newLen; i++) {
            elems[i] = new Elem();
            elems[i].value = new AnyValue(parentModifiedFields, parentModifiedBit);
        }
        if (initedCount < newLen) {
            initedCount = newLen;
        }
        markModified();
    }

    private void markModified() {
        if (parentModifiedFields != null) {
            parentModifiedFields.markModified(parentModifiedBit);
        }
    }

    public boolean isModified() {
        return parentModifiedFields != null && parentModifiedFields.isModified(parentModifiedBit);
    }

    public void markUnmodified() {
        if (parentModifiedFields != null) {
            parentModifiedFields.markUnmodified();
        }
    }

    public void markUnmodifiedRecursively() {
        for (Elem elem : elems) {
            // TODO: recursive markUnmodified for key/value if not primitive
        }
    }

    // Append adds a key-value pair to the multimap.
    public void append(StringValue k, AnyValue v) {
        ensureElems(elemsLen + 1);
        Elem elem = new Elem();
        elem.key = k;
        elem.value = v;
        elems[elemsLen++] = elem;
        markModified();
    }

    // SetKey sets the key of the element at index i.
    public void setKey(int i, StringValue k) {
        if (!Types.StringEqual(elems[i].key, k)) {
            elems[i].key = k;
            markModified();
        }
    }

    // SetValue sets the value of the element at index i.
    public void setValue(int i, AnyValue v) {
        if (!AnyValue.isEqual(elems[i].value, v)) {
            elems[i].value = v;
            markModified();
        }
    }

    // Sorts the multimap by key.
    public void sort() {
        Arrays.sort(elems, 0, elemsLen, new Comparator<Elem>() {
            @Override
            public int compare(Elem a, Elem b) {
                return Types.StringCompare(a.key, b.key);
            }
        });
    }

    // ByteSize returns approximate memory usage in bytes. Used to calculate
    // memory used by dictionaries.
    public int byteSize() {
        int size = 0;
        size += this.elemsLen * 16; // TODO: estimate size of Elem objects
        return size;
    }

    // Copy all elements from src to this multimap.
    public void copyFrom(KeyValueList src) {
        boolean modified = false;
        if (elemsLen!=src.elemsLen) {
            ensureLen(src.elemsLen);
            modified = true;
        }
        for (int i=0; i < src.elemsLen; i++) {
            if (elems[i].key != src.elems[i].key) {
                elems[i].key = src.elems[i].key;
                modified = true;
            }
        
            if (!AnyValue.isEqual(elems[i].value, src.elems[i].value)) {
                elems[i].value.copyFrom(src.elems[i].value);
                modified = true;
            }
        }
        
        if (modified) {
            markModified();
        }
    }

    // IsEqual performs deep comparison and returns true if this multimap is equal to val.
    public boolean isEqual(KeyValueList val) {
        if (elemsLen != val.elemsLen) {
            return false;
        }
        for (int i = 0; i<elemsLen; i++) {
            if (!Types.StringEqual(elems[i].key,val.elems[i].key)) {
                return false;
            }
            if (!elems[i].value.isEqual(val.elems[i].value)) {
                return false;
            }
        }
        return true;
    }

    // compare compares two multimaps lexicographically.
    public static int compare(KeyValueList left, KeyValueList right) {
        int l = Math.min(left.elemsLen, right.elemsLen);
        for (int i = 0; i < l; i++) {
            int c = Types.StringCompare(left.elems[i].key, right.elems[i].key);
            if (c != 0) return c;
        }
    
        int lenDiff = left.elemsLen - right.elemsLen;
        if (lenDiff != 0) {
            return lenDiff;
        }
    
        for (int i = 0; i < l; i++) {
            int c = AnyValue.compare(left.elems[i].value, right.elems[i].value);
            if (c != 0) return c;
        }
        return 0;
    }

    // mutateRandom mutates fields in a random, deterministic manner using random parameter as a deterministic generator.
    public void mutateRandom(Random random) {
        if (random.nextInt(20) == 0) {
            ensureLen(elemsLen + 1);
        }
        if (random.nextInt(20) == 0 && elemsLen > 0) {
            ensureLen(elemsLen - 1);
        }
        for (int i = 0; i < elemsLen; i++) {
            if (random.nextInt(4 * elemsLen) == 0) {
                setKey(i, Types.StringRandom(random));
            }
            if (random.nextInt(4 * elemsLen) == 0) {
                elems[i].value.mutateRandom(random);
            }
        }
    }

    // Helper for copying multimaps
    public static void copyKeyValueList(KeyValueList dst, KeyValueList src) {
        dst.ensureLen(src.elemsLen);
        for (int i = 0; i < src.elemsLen; i++) {
            dst.elems[i].key = src.elems[i].key;
            dst.elems[i].value = src.elems[i].value;
        }
        dst.markModified();
    }

    boolean isSameKeys(KeyValueList val2) {
        if (elemsLen != val2.elemsLen) {
            return false;
        }

        for (int i=0; i<elemsLen; i++) {
            if (elems[i].key != val2.elems[i].key) {
                return false;
            }
        }

        return true;
    }
}
