// Code generated by stefgen. DO NOT EDIT.
// MetricDecoder implements decoding of Metric
package com.example.oteltef;

import net.stef.BitsReader;
import net.stef.ReadColumnSet;
import net.stef.ReadableColumn;
import net.stef.codecs.*;

import java.io.IOException;

class MetricDecoder {
    private final BitsReader buf = new BitsReader();
    private ReadableColumn column;
    private Metric lastVal;
    private int fieldCount;

    
    private StringDecoder nameDecoder = new StringDecoder();
    private StringDecoder descriptionDecoder = new StringDecoder();
    private StringDecoder unitDecoder = new StringDecoder();
    private Uint64Decoder type_Decoder = new Uint64Decoder();
    private AttributesDecoder metadataDecoder = new AttributesDecoder();
    private Float64ArrayDecoder histogramBoundsDecoder = new Float64ArrayDecoder();
    private Uint64Decoder aggregationTemporalityDecoder = new Uint64Decoder();
    private BoolDecoder monotonicDecoder = new BoolDecoder();
    
    private MetricDecoderDict dict;
    

    // Init is called once in the lifetime of the stream.
    public void init(ReaderState state, ReadColumnSet columns) throws IOException {
        // Remember this encoder in the state so that we can detect recursion.
        if (state.MetricDecoder != null) {
            throw new IllegalStateException("cannot initialize MetricDecoder: already initialized");
        }
        state.MetricDecoder = this;

        try {
            if (state.getOverrideSchema() != null) {
                int fieldCount = state.getOverrideSchema().getFieldCount("Metric");
                fieldCount = fieldCount;
            } else {
                fieldCount = 8;
            }
            column = columns.getColumn();
            
            lastVal = new Metric(null, 0);
            dict = state.Metric;
            
            if (this.fieldCount <= 0) {
                return; // Name and subsequent fields are skipped.
            }
            nameDecoder.init(state.MetricName, columns.addSubColumn());
            if (this.fieldCount <= 1) {
                return; // Description and subsequent fields are skipped.
            }
            descriptionDecoder.init(state.MetricDescription, columns.addSubColumn());
            if (this.fieldCount <= 2) {
                return; // Unit and subsequent fields are skipped.
            }
            unitDecoder.init(state.MetricUnit, columns.addSubColumn());
            if (this.fieldCount <= 3) {
                return; // Type and subsequent fields are skipped.
            }
            type_Decoder.init(columns.addSubColumn());
            if (this.fieldCount <= 4) {
                return; // Metadata and subsequent fields are skipped.
            }
            metadataDecoder.init(state, columns.addSubColumn());
            if (this.fieldCount <= 5) {
                return; // HistogramBounds and subsequent fields are skipped.
            }
            histogramBoundsDecoder.init(state, columns.addSubColumn());
            if (this.fieldCount <= 6) {
                return; // AggregationTemporality and subsequent fields are skipped.
            }
            aggregationTemporalityDecoder.init(columns.addSubColumn());
            if (this.fieldCount <= 7) {
                return; // Monotonic and subsequent fields are skipped.
            }
            monotonicDecoder.init(columns.addSubColumn());
        } finally {
            state.MetricDecoder = null;
        }
    }

    // continueDecoding is called at the start of the frame to continue decoding column data.
    // This should set the decoder's source buffer, so the new decoding continues from
    // the supplied column data. This should NOT reset the internal state of the decoder,
    // since columns can cross frame boundaries and the new column data is considered
    // continuation of that same column in the previous frame.
    public void continueDecoding() {
        this.buf.reset(this.column.getData());
        
        if (this.fieldCount <= 0) {
            return; // Name and subsequent fields are skipped.
        }
        this.nameDecoder.continueDecoding();
        if (this.fieldCount <= 1) {
            return; // Description and subsequent fields are skipped.
        }
        this.descriptionDecoder.continueDecoding();
        if (this.fieldCount <= 2) {
            return; // Unit and subsequent fields are skipped.
        }
        this.unitDecoder.continueDecoding();
        if (this.fieldCount <= 3) {
            return; // Type and subsequent fields are skipped.
        }
        this.type_Decoder.continueDecoding();
        if (this.fieldCount <= 4) {
            return; // Metadata and subsequent fields are skipped.
        }
        this.metadataDecoder.continueDecoding();
        if (this.fieldCount <= 5) {
            return; // HistogramBounds and subsequent fields are skipped.
        }
        this.histogramBoundsDecoder.continueDecoding();
        if (this.fieldCount <= 6) {
            return; // AggregationTemporality and subsequent fields are skipped.
        }
        this.aggregationTemporalityDecoder.continueDecoding();
        if (this.fieldCount <= 7) {
            return; // Monotonic and subsequent fields are skipped.
        }
        this.monotonicDecoder.continueDecoding();
    }

    public void reset() {
        this.nameDecoder.reset();
        this.descriptionDecoder.reset();
        this.unitDecoder.reset();
        this.type_Decoder.reset();
        this.metadataDecoder.reset();
        this.histogramBoundsDecoder.reset();
        this.aggregationTemporalityDecoder.reset();
        this.monotonicDecoder.reset();
    }

    public Metric decode(Metric dstPtr) throws IOException {
        // Check if the Metric exists in the dictionary.
        int dictFlag = buf.readBit();
        if (dictFlag == 0) {
            long refNum = buf.readUvarintCompact();
            if (refNum >= dict.size()) {
                throw new IOException("Invalid refNum");
            }
            lastVal = dict.getByIndex((int)refNum);
            dstPtr = lastVal;
            return dstPtr;
        }

        // lastValPtr here is pointing to an element in the dictionary. We are not allowed
        // to modify it. Make a clone of it and decode into the clone.
        Metric val = lastVal.clone();
        lastVal = val;
        dstPtr = val;
        // Read bits that indicate which fields follow.
        val.modifiedFields.mask = buf.readBits(fieldCount);
        
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedName) != 0) {
            // Field is changed and is present, decode it.
            val.name = nameDecoder.decode();
        }
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedDescription) != 0) {
            // Field is changed and is present, decode it.
            val.description = descriptionDecoder.decode();
        }
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedUnit) != 0) {
            // Field is changed and is present, decode it.
            val.unit = unitDecoder.decode();
        }
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedType) != 0) {
            // Field is changed and is present, decode it.
            val.type_ = type_Decoder.decode();
        }
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedMetadata) != 0) {
            // Field is changed and is present, decode it.
            val.metadata = metadataDecoder.decode(val.metadata);
        }
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedHistogramBounds) != 0) {
            // Field is changed and is present, decode it.
            val.histogramBounds = histogramBoundsDecoder.decode(val.histogramBounds);
        }
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedAggregationTemporality) != 0) {
            // Field is changed and is present, decode it.
            val.aggregationTemporality = aggregationTemporalityDecoder.decode();
        }
        
        if ((val.modifiedFields.mask & Metric.fieldModifiedMonotonic) != 0) {
            // Field is changed and is present, decode it.
            val.monotonic = monotonicDecoder.decode();
        }
        
        
        dict.add(val);
        
        return val;
    }
}

