// Code generated by stefgen. DO NOT EDIT.
// PointValueDecoder implements decoding of PointValue
package com.example.oteltef;

import net.stef.BitsReader;
import net.stef.ReadColumnSet;
import net.stef.ReadableColumn;
import net.stef.codecs.*;

public class PointValueDecoder {
    private final BitsReader buf = new BitsReader();
    private ReadableColumn column;
    private PointValue lastValPtr;
    private PointValue lastVal = new PointValue();
    private int fieldCount;

    
    private Int64Decoder int64Decoder = new Int64Decoder();
    private Float64Decoder float64Decoder = new Float64Decoder();
    private HistogramValueDecoder histogramDecoder = new HistogramValueDecoder();
    

    // Init is called once in the lifetime of the stream.
    public void init(ReaderState state, ReadColumnSet columns) throws Exception {
        state.PointValueDecoder = this;
        if (state.getOverrideSchema() != null) {
            int fieldCount = state.getOverrideSchema().getFieldCount("PointValue");
            this.fieldCount = fieldCount;
        } else {
            this.fieldCount = 3;
        }
        this.column = columns.getColumn();
        this.lastVal.init(null, 0);
        this.lastValPtr = this.lastVal;
        Exception err = null;
        
        if (this.fieldCount <= 0) {
            return; // Int64 and subsequent fields are skipped.
        }
        this.int64Decoder.init(columns.addSubColumn());
        if (this.fieldCount <= 1) {
            return; // Float64 and subsequent fields are skipped.
        }
        this.float64Decoder.init(columns.addSubColumn());
        if (this.fieldCount <= 2) {
            return; // Histogram and subsequent fields are skipped.
        }
        this.histogramDecoder.init(state, columns.addSubColumn());
    }

    // Decode decodes a value from the buffer into dst.
    public PointValue decode(PointValue dst) throws Exception {
        // Read type delta
        long typeDelta = this.buf.readVarintCompact();
        int typ = (this.lastValPtr != null ? this.lastValPtr.getType().ordinal() : 0) + (int)typeDelta;
        if (typ < 0 || typ >= PointValue.Type.values().length) {
            throw new Exception("Invalid oneof type");
        }
        dst.setType(PointValue.Type.values()[typ]);
        this.lastValPtr = dst;
        // Decode selected field
        switch (dst.getType()) {
            case PointValue.Type.TypeInt64:
                dst.int64 = this.int64Decoder.decode();
                break;
            case PointValue.Type.TypeFloat64:
                dst.float64 = this.float64Decoder.decode();
                break;
            case PointValue.Type.TypeHistogram:
                dst.histogram = this.histogramDecoder.decode(dst.histogram);
                break;
            default:
                break;
        }
        return dst;
    }
}
