// Code generated by stefc. DO NOT EDIT.
package jsonstef

import (
	"fmt"
	"math/bits"
	"math/rand/v2"
	"strings"
	"unsafe"

	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/codecs"
	"github.com/splunk/stef/go/pkg/schema"
)

var _ = strings.Compare
var _ = codecs.StringEncoder{}

// JsonValue is a oneof struct.
type JsonValue struct {
	// The current type of the oneof.
	typ JsonValueType

	object JsonObject
	array  JsonValueArray
	string string
	number float64
	bool   bool

	// Pointer to parent's modifiedFields
	parentModifiedFields *modifiedFields
	// Bit to set in parent's modifiedFields when this oneof is modified.
	parentModifiedBit uint64
}

// Init must be called once, before the JsonValue is used.
func (s *JsonValue) Init() {
	s.init(nil, 0)
}

func (s *JsonValue) init(parentModifiedFields *modifiedFields, parentModifiedBit uint64) {
	s.parentModifiedFields = parentModifiedFields
	s.parentModifiedBit = parentModifiedBit

	s.object.init(parentModifiedFields, parentModifiedBit)
	s.array.init(parentModifiedFields, parentModifiedBit)
}

func (s *JsonValue) initAlloc(parentModifiedFields *modifiedFields, parentModifiedBit uint64, allocators *Allocators) {
	s.parentModifiedFields = parentModifiedFields
	s.parentModifiedBit = parentModifiedBit

	s.object.initAlloc(parentModifiedFields, parentModifiedBit, allocators)
	s.array.initAlloc(parentModifiedFields, parentModifiedBit, allocators)
}

// reset the struct to its initial state, as if init() was just called.
// Will not reset internal fields such as parentModifiedFields.
func (s *JsonValue) reset() {
	s.typ = JsonValueTypeNone
	// We don't need to reset the state of the field since that will be done
	// when the type is changed, see SetType().
}

func (s *JsonValue) freeze() {
	switch s.typ {
	case JsonValueTypeObject:
		s.object.freeze()
	case JsonValueTypeArray:
		s.array.freeze()
	}
}

// fixParent sets the parentModifiedFields pointer to the supplied value.
// This is used when the parent is moved in memory for example because the parent
// an array element and the array was expanded.
func (s *JsonValue) fixParent(parentModifiedFields *modifiedFields) {
	s.parentModifiedFields = parentModifiedFields

	s.object.fixParent(parentModifiedFields)
	s.array.fixParent(parentModifiedFields)
}

type JsonValueType byte

const (
	JsonValueTypeNone = JsonValueType(iota)
	JsonValueTypeObject
	JsonValueTypeArray
	JsonValueTypeString
	JsonValueTypeNumber
	JsonValueTypeBool
	JsonValueTypeCount
)

// Type returns the type of the value currently contained in JsonValue.
func (s *JsonValue) Type() JsonValueType {
	return s.typ
}

// resetContained resets the currently contained value, if any.
// Normally used after switching to a different type to make sure
// the value contained is in blank state.
func (s *JsonValue) resetContained() {
	switch s.typ {
	case JsonValueTypeObject:
		s.object.reset()
	case JsonValueTypeArray:
		s.array.reset()
	}
}

// SetType sets the type of the value currently contained in JsonValue.
func (s *JsonValue) SetType(typ JsonValueType) {
	if s.typ != typ {
		s.typ = typ
		s.resetContained()
		switch typ {
		}
		s.markParentModified()
	}
}

// Object returns the value if the contained type is currently JsonValueTypeObject.
// The caller must check the type via Type() before attempting to call this function.
func (s *JsonValue) Object() *JsonObject {
	return &s.object
}

// Array returns the value if the contained type is currently JsonValueTypeArray.
// The caller must check the type via Type() before attempting to call this function.
func (s *JsonValue) Array() *JsonValueArray {
	return &s.array
}

// String returns the value if the contained type is currently JsonValueTypeString.
// The caller must check the type via Type() before attempting to call this function.
func (s *JsonValue) String() string {
	return s.string
}

// SetString sets the value to the specified value and sets the type to JsonValueTypeString.
func (s *JsonValue) SetString(v string) {
	if s.typ != JsonValueTypeString || s.string != v {
		s.string = v
		s.typ = JsonValueTypeString
		s.parentModifiedFields.markModified(s.parentModifiedBit)
	}
}

// Number returns the value if the contained type is currently JsonValueTypeNumber.
// The caller must check the type via Type() before attempting to call this function.
func (s *JsonValue) Number() float64 {
	return s.number
}

// SetNumber sets the value to the specified value and sets the type to JsonValueTypeNumber.
func (s *JsonValue) SetNumber(v float64) {
	if s.typ != JsonValueTypeNumber || s.number != v {
		s.number = v
		s.typ = JsonValueTypeNumber
		s.parentModifiedFields.markModified(s.parentModifiedBit)
	}
}

// Bool returns the value if the contained type is currently JsonValueTypeBool.
// The caller must check the type via Type() before attempting to call this function.
func (s *JsonValue) Bool() bool {
	return s.bool
}

// SetBool sets the value to the specified value and sets the type to JsonValueTypeBool.
func (s *JsonValue) SetBool(v bool) {
	if s.typ != JsonValueTypeBool || s.bool != v {
		s.bool = v
		s.typ = JsonValueTypeBool
		s.parentModifiedFields.markModified(s.parentModifiedBit)
	}
}

func (s *JsonValue) canBeShared() bool {
	// Oneof can never be shared.
	return false
}

func (s *JsonValue) cloneShared(allocators *Allocators) *JsonValue {
	// Oneof is not shareable, so cloneShared is just a Clone.
	return s.Clone(allocators)
}

func (s *JsonValue) Clone(allocators *Allocators) *JsonValue {
	allocators.addAllocSize(int(unsafe.Sizeof(JsonValue{})))
	c := allocators.JsonValue.Alloc()
	c.typ = s.typ
	switch s.typ {
	case JsonValueTypeObject:
		copyToNewJsonObject(&c.object, &s.object, allocators)
	case JsonValueTypeArray:
		copyToNewJsonValueArray(&c.array, &s.array, allocators)
	case JsonValueTypeString:
		c.string = s.string
	case JsonValueTypeNumber:
		c.number = s.number
	case JsonValueTypeBool:
		c.bool = s.bool
	}
	return c
}

// ByteSize returns approximate memory usage in bytes. Used to calculate
// memory used by dictionaries.
func (s *JsonValue) byteSize() uint {
	return uint(unsafe.Sizeof(*s)) +
		s.object.byteSize() + s.array.byteSize() + 0
}

// Copy from src to dst, overwriting existing data in dst.
func copyJsonValue(dst *JsonValue, src *JsonValue) {
	switch src.typ {
	case JsonValueTypeObject:
		dst.SetType(src.typ)
		copyJsonObject(&dst.object, &src.object)
	case JsonValueTypeArray:
		dst.SetType(src.typ)
		copyJsonValueArray(&dst.array, &src.array)
	case JsonValueTypeString:
		dst.SetString(src.string)
	case JsonValueTypeNumber:
		dst.SetNumber(src.number)
	case JsonValueTypeBool:
		dst.SetBool(src.bool)
	case JsonValueTypeNone:
		if dst.typ != JsonValueTypeNone {
			dst.typ = JsonValueTypeNone
			dst.markParentModified()
		}
	default:
		panic("copyJsonValue: unexpected type: " + fmt.Sprint(src.typ))
	}
}

// Copy from src to dst. dst is assumed to be just inited.
func copyToNewJsonValue(dst *JsonValue, src *JsonValue, allocators *Allocators) {
	dst.typ = src.typ
	switch src.typ {
	case JsonValueTypeObject:
		copyToNewJsonObject(&dst.object, &src.object, allocators)
	case JsonValueTypeArray:
		copyToNewJsonValueArray(&dst.array, &src.array, allocators)
	case JsonValueTypeString:
		if dst.string != src.string {
			dst.string = src.string
			dst.parentModifiedFields.markModified(dst.parentModifiedBit)
		}
	case JsonValueTypeNumber:
		if dst.number != src.number {
			dst.number = src.number
			dst.parentModifiedFields.markModified(dst.parentModifiedBit)
		}
	case JsonValueTypeBool:
		if dst.bool != src.bool {
			dst.bool = src.bool
			dst.parentModifiedFields.markModified(dst.parentModifiedBit)
		}
	case JsonValueTypeNone:
	default:
		panic("copyJsonValue: unexpected type: " + fmt.Sprint(src.typ))
	}
}

// CopyFrom() performs a deep copy from src.
func (s *JsonValue) CopyFrom(src *JsonValue) {
	copyJsonValue(s, src)
}

func (s *JsonValue) markParentModified() {
	s.parentModifiedFields.markModified(s.parentModifiedBit)
}

func (s *JsonValue) setModifiedRecursively() {
	switch s.typ {
	case JsonValueTypeObject:
		s.object.setModifiedRecursively()
	case JsonValueTypeArray:
		s.array.setModifiedRecursively()
	}
}

func (s *JsonValue) setUnmodifiedRecursively() {
	switch s.typ {
	case JsonValueTypeObject:
		s.object.setUnmodifiedRecursively()
	case JsonValueTypeArray:
		s.array.setUnmodifiedRecursively()
	}
}

// computeDiff compares s and val and returns true if they differ.
// All fields that are different in s will be marked as modified.
func (s *JsonValue) computeDiff(val *JsonValue) (ret bool) {
	if s.typ == val.typ {
		switch s.typ {
		case JsonValueTypeObject:
			ret = s.object.computeDiff(&val.object)
		case JsonValueTypeArray:
			ret = s.array.computeDiff(&val.array)
		case JsonValueTypeString:
			ret = s.string != val.string
		case JsonValueTypeNumber:
			ret = s.number != val.number
		case JsonValueTypeBool:
			ret = s.bool != val.bool
		}
	} else {
		ret = true
		switch s.typ {
		case JsonValueTypeObject:
			// val.object doesn't exist at all so mark the whole s.object subtree as modified.
			s.object.setModifiedRecursively()
		case JsonValueTypeArray:
			// val.array doesn't exist at all so mark the whole s.array subtree as modified.
			s.array.setModifiedRecursively()
		}
	}
	return ret
}

// IsEqual performs deep comparison and returns true if struct is equal to val.
func (e *JsonValue) IsEqual(val *JsonValue) bool {
	if e.typ != val.typ {
		return false
	}
	switch e.typ {
	case JsonValueTypeObject:
		return e.object.IsEqual(&val.object)
	case JsonValueTypeArray:
		return e.array.IsEqual(&val.array)
	case JsonValueTypeString:
		return pkg.StringEqual(e.string, val.string)
	case JsonValueTypeNumber:
		return pkg.Float64Equal(e.number, val.number)
	case JsonValueTypeBool:
		return pkg.BoolEqual(e.bool, val.bool)
	}

	return true
}

// CmpJsonValue performs deep comparison and returns an integer that
// will be 0 if left == right, negative if left < right, positive if left > right.
func CmpJsonValue(left, right *JsonValue) int {
	c := pkg.Uint64Compare(uint64(left.typ), uint64(right.typ))
	if c != 0 {
		return c
	}
	switch left.typ {
	case JsonValueTypeObject:
		return CmpJsonObject(&left.object, &right.object)
	case JsonValueTypeArray:
		return CmpJsonValueArray(&left.array, &right.array)
	case JsonValueTypeString:
		return strings.Compare(left.string, right.string)
	case JsonValueTypeNumber:
		return pkg.Float64Compare(left.number, right.number)
	case JsonValueTypeBool:
		return pkg.BoolCompare(left.bool, right.bool)
	}

	return 0
}

// mutateRandom mutates fields in a random, deterministic manner using
// random parameter as a deterministic generator. Only fields that exist
// in the schema are mutated, allowing to generate data for specified schema.
func (s *JsonValue) mutateRandom(random *rand.Rand, schem *schema.Schema, limiter *mutateRandomLimiter) {
	// Get the field count for this oneof from the schema. If the schema specifies
	// fewer field count than the one we have in this code then we will not mutate
	// the type of the oneof to the choices that are not in the schema.
	fieldCount, err := schem.FieldCount("JsonValue")
	if err != nil {
		panic(fmt.Sprintf("cannot get field count for %s: %v", "JsonValue", err))
	}

	typeChanged := false
	if random.IntN(10) == 0 {
		s.SetType(JsonValueType(random.IntN(fieldCount + 1)))
		typeChanged = true
	}

	switch s.typ {
	case JsonValueTypeObject:
		if typeChanged || random.IntN(2) == 0 {
			s.object.mutateRandom(random, schem, limiter)
		}
	case JsonValueTypeArray:
		if typeChanged || random.IntN(2) == 0 {
			s.array.mutateRandom(random, schem, limiter)
		}
	case JsonValueTypeString:
		if typeChanged || random.IntN(2) == 0 {
			s.SetString(pkg.StringRandom(random))
		}
	case JsonValueTypeNumber:
		if typeChanged || random.IntN(2) == 0 {
			s.SetNumber(pkg.Float64Random(random))
		}
	case JsonValueTypeBool:
		if typeChanged || random.IntN(2) == 0 {
			s.SetBool(pkg.BoolRandom(random))
		}
	}
}

// JsonValueEncoder implements encoding of JsonValue
type JsonValueEncoder struct {
	buf     pkg.BitsWriter
	limiter *pkg.SizeLimiter

	// fieldCount is the number of fields, i.e. the number of types in this oneof.
	fieldCount uint
	// Number of bits needed to encode the type (including None type).
	typeBitCount uint

	// Field encoders.
	objectEncoder     *JsonObjectEncoder
	isObjectRecursive bool // Indicates Object field's type is recursive.

	arrayEncoder     *JsonValueArrayEncoder
	isArrayRecursive bool // Indicates Array field's type is recursive.

	stringEncoder codecs.StringEncoder

	numberEncoder codecs.Float64Encoder

	boolEncoder codecs.BoolEncoder
}

func (e *JsonValueEncoder) Init(state *WriterState, columns *pkg.WriteColumnSet) error {
	// Remember this encoder in the state so that we can detect recursion.
	if state.JsonValueEncoder != nil {
		panic("cannot initialize JsonValueEncoder: already initialized")
	}
	state.JsonValueEncoder = e
	defer func() { state.JsonValueEncoder = nil }()

	e.limiter = &state.limiter

	var err error
	e.fieldCount, err = state.StructFieldCounts.JsonValueFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %w", "JsonValue", err)
	}
	e.typeBitCount = uint(bits.Len64(uint64(e.fieldCount) + 1))

	// Init encoder for Object field.
	if e.fieldCount <= 0 {
		// Object and all subsequent fields are skipped.
		return nil
	}
	if state.JsonObjectEncoder != nil {
		// Recursion detected, use the existing encoder.
		e.objectEncoder = state.JsonObjectEncoder
		e.isObjectRecursive = true
	} else {
		e.objectEncoder = new(JsonObjectEncoder)
		err = e.objectEncoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}

	// Init encoder for Array field.
	if e.fieldCount <= 1 {
		// Array and all subsequent fields are skipped.
		return nil
	}
	if state.JsonValueArrayEncoder != nil {
		// Recursion detected, use the existing encoder.
		e.arrayEncoder = state.JsonValueArrayEncoder
		e.isArrayRecursive = true
	} else {
		e.arrayEncoder = new(JsonValueArrayEncoder)
		err = e.arrayEncoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}

	// Init encoder for String field.
	if e.fieldCount <= 2 {
		// String and all subsequent fields are skipped.
		return nil
	}
	err = e.stringEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	// Init encoder for Number field.
	if e.fieldCount <= 3 {
		// Number and all subsequent fields are skipped.
		return nil
	}
	err = e.numberEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	// Init encoder for Bool field.
	if e.fieldCount <= 4 {
		// Bool and all subsequent fields are skipped.
		return nil
	}
	err = e.boolEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

func (e *JsonValueEncoder) Reset() {

	if e.fieldCount <= 0 {
		return // Object and all subsequent fields are skipped.
	}

	if !e.isObjectRecursive {
		e.objectEncoder.Reset()
	}

	if e.fieldCount <= 1 {
		return // Array and all subsequent fields are skipped.
	}

	if !e.isArrayRecursive {
		e.arrayEncoder.Reset()
	}

	if e.fieldCount <= 2 {
		return // String and all subsequent fields are skipped.
	}
	e.stringEncoder.Reset()
	if e.fieldCount <= 3 {
		return // Number and all subsequent fields are skipped.
	}
	e.numberEncoder.Reset()
	if e.fieldCount <= 4 {
		return // Bool and all subsequent fields are skipped.
	}
	e.boolEncoder.Reset()
}

// Encode encodes val into buf
func (e *JsonValueEncoder) Encode(val *JsonValue) {
	typ := val.typ
	if uint(typ) > e.fieldCount {
		// The current field type is not supported in target schema. Encode the type as None.
		typ = JsonValueTypeNone
	}

	e.buf.WriteBits(uint64(typ), e.typeBitCount)

	// Account written bits in the limiter.
	e.limiter.AddFrameBits(e.typeBitCount)

	// Encode currently selected field.
	switch typ {
	case JsonValueTypeObject:
		// Encode Object
		e.objectEncoder.Encode(&val.object)
	case JsonValueTypeArray:
		// Encode Array
		e.arrayEncoder.Encode(&val.array)
	case JsonValueTypeString:
		// Encode String
		e.stringEncoder.Encode(val.string)
	case JsonValueTypeNumber:
		// Encode Number
		e.numberEncoder.Encode(val.number)
	case JsonValueTypeBool:
		// Encode Bool
		e.boolEncoder.Encode(val.bool)
	}
}

// CollectColumns collects all buffers from all encoders into buf.
func (e *JsonValueEncoder) CollectColumns(columnSet *pkg.WriteColumnSet) {
	columnSet.SetBits(&e.buf)
	colIdx := 0

	// Collect Object field.
	if e.fieldCount <= 0 {
		return // Object and subsequent fields are skipped.
	}
	if !e.isObjectRecursive {
		e.objectEncoder.CollectColumns(columnSet.At(colIdx))
		colIdx++
	}

	// Collect Array field.
	if e.fieldCount <= 1 {
		return // Array and subsequent fields are skipped.
	}
	if !e.isArrayRecursive {
		e.arrayEncoder.CollectColumns(columnSet.At(colIdx))
		colIdx++
	}

	// Collect String field.
	if e.fieldCount <= 2 {
		return // String and subsequent fields are skipped.
	}

	e.stringEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++

	// Collect Number field.
	if e.fieldCount <= 3 {
		return // Number and subsequent fields are skipped.
	}

	e.numberEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++

	// Collect Bool field.
	if e.fieldCount <= 4 {
		return // Bool and subsequent fields are skipped.
	}

	e.boolEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++
}

// JsonValueDecoder implements decoding of JsonValue
type JsonValueDecoder struct {
	buf        pkg.BitsReader
	column     *pkg.ReadableColumn
	lastValPtr *JsonValue
	lastVal    JsonValue

	// fieldCount is the number of fields, i.e. the number of types in this oneof.
	fieldCount uint
	// Number of bits needed to encode the type (including None type).
	typeBitCount uint

	// Field decoders.

	objectDecoder     *JsonObjectDecoder
	isObjectRecursive bool

	arrayDecoder     *JsonValueArrayDecoder
	isArrayRecursive bool

	stringDecoder codecs.StringDecoder

	numberDecoder codecs.Float64Decoder

	boolDecoder codecs.BoolDecoder

	allocators *Allocators
}

// Init is called once in the lifetime of the stream.
func (d *JsonValueDecoder) Init(state *ReaderState, columns *pkg.ReadColumnSet) error {
	// Remember this decoder in the state so that we can detect recursion.
	if state.JsonValueDecoder != nil {
		panic("cannot initialize JsonValueDecoder: already initialized")
	}
	state.JsonValueDecoder = d
	defer func() { state.JsonValueDecoder = nil }()

	d.allocators = &state.Allocators

	var err error
	d.fieldCount, err = state.StructFieldCounts.JsonValueFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %w", "JsonValue", err)
	}

	d.column = columns.Column()

	d.lastVal.init(nil, 0)
	d.lastValPtr = &d.lastVal

	d.typeBitCount = uint(bits.Len64(uint64(d.fieldCount) + 1))
	if d.fieldCount <= 0 {
		return nil // Object and subsequent fields are skipped.
	}
	if state.JsonObjectDecoder != nil {
		// Recursion detected, use the existing decoder.
		d.objectDecoder = state.JsonObjectDecoder
		d.isObjectRecursive = true // Mark that we are using a recursive decoder.
	} else {
		d.objectDecoder = new(JsonObjectDecoder)
		err = d.objectDecoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}
	if d.fieldCount <= 1 {
		return nil // Array and subsequent fields are skipped.
	}
	if state.JsonValueArrayDecoder != nil {
		// Recursion detected, use the existing decoder.
		d.arrayDecoder = state.JsonValueArrayDecoder
		d.isArrayRecursive = true // Mark that we are using a recursive decoder.
	} else {
		d.arrayDecoder = new(JsonValueArrayDecoder)
		err = d.arrayDecoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}
	if d.fieldCount <= 2 {
		return nil // String and subsequent fields are skipped.
	}
	err = d.stringDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 3 {
		return nil // Number and subsequent fields are skipped.
	}
	err = d.numberDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 4 {
		return nil // Bool and subsequent fields are skipped.
	}
	err = d.boolDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

// Continue is called at the start of the frame to continue decoding column data.
// This should set the decoder's source buffer, so the new decoding continues from
// the supplied column data. This should NOT reset the internal state of the decoder,
// since columns can cross frame boundaries and the new column data is considered
// continuation of that same column in the previous frame.
func (d *JsonValueDecoder) Continue() {
	d.buf.Reset(d.column.Data())

	if d.fieldCount <= 0 {
		return // Object and subsequent fields are skipped.
	}

	if !d.isObjectRecursive {
		d.objectDecoder.Continue()
	}

	if d.fieldCount <= 1 {
		return // Array and subsequent fields are skipped.
	}

	if !d.isArrayRecursive {
		d.arrayDecoder.Continue()
	}

	if d.fieldCount <= 2 {
		return // String and subsequent fields are skipped.
	}
	d.stringDecoder.Continue()

	if d.fieldCount <= 3 {
		return // Number and subsequent fields are skipped.
	}
	d.numberDecoder.Continue()

	if d.fieldCount <= 4 {
		return // Bool and subsequent fields are skipped.
	}
	d.boolDecoder.Continue()

}

func (d *JsonValueDecoder) Reset() {

	if d.fieldCount <= 0 {
		return // Object and all subsequent fields are skipped.
	}

	if !d.isObjectRecursive {
		d.objectDecoder.Reset()
	}

	if d.fieldCount <= 1 {
		return // Array and all subsequent fields are skipped.
	}

	if !d.isArrayRecursive {
		d.arrayDecoder.Reset()
	}

	if d.fieldCount <= 2 {
		return // String and all subsequent fields are skipped.
	}
	d.stringDecoder.Reset()
	if d.fieldCount <= 3 {
		return // Number and all subsequent fields are skipped.
	}
	d.numberDecoder.Reset()
	if d.fieldCount <= 4 {
		return // Bool and all subsequent fields are skipped.
	}
	d.boolDecoder.Reset()
}

func (d *JsonValueDecoder) Decode(dstPtr *JsonValue) error {
	// Read the type and validate it
	typ := uint(d.buf.ReadBits(d.typeBitCount))
	if typ >= uint(d.fieldCount+1) {
		return pkg.ErrInvalidOneOfType
	}

	dst := dstPtr
	if dst.typ != JsonValueType(typ) {
		dst.typ = JsonValueType(typ)
		// The type changed, we need to reset the contained value so that
		// it does not contain carry-over data from a previous record that
		// was of this same type.
		dst.resetContained()
	}

	// Decode selected field
	switch dst.typ {
	case JsonValueTypeObject:
		// Decode Object
		return d.objectDecoder.Decode(&dst.object)
	case JsonValueTypeArray:
		// Decode Array
		return d.arrayDecoder.Decode(&dst.array)
	case JsonValueTypeString:
		// Decode String
		return d.stringDecoder.Decode(&dst.string)
	case JsonValueTypeNumber:
		// Decode Number
		return d.numberDecoder.Decode(&dst.number)
	case JsonValueTypeBool:
		// Decode Bool
		return d.boolDecoder.Decode(&dst.bool)
	}
	return d.buf.Error()
}

// JsonValueAllocator implements a custom allocator for JsonValue.
// It maintains a pool of pre-allocated JsonValue and grows the pool
// dynamically as needed, up to a maximum size of 64 elements.
type JsonValueAllocator struct {
	pool []JsonValue
	ofs  int
}

// Alloc returns the next available JsonValue from the pool.
// If the pool is exhausted, it grows the pool by doubling its size
// up to a maximum of 64 elements.
func (a *JsonValueAllocator) Alloc() *JsonValue {
	if a.ofs < len(a.pool) {
		// Get the next available JsonValue from the pool
		a.ofs++
		return &a.pool[a.ofs-1]
	}
	// We've exhausted the current pool, prealloc a new pool.
	return a.prealloc()
}

//go:noinline
func (a *JsonValueAllocator) prealloc() *JsonValue {
	// prealloc expands the pool by doubling its size, up to a maximum of 64 elements.
	// If the pool is empty, it starts with 1 element.
	newLen := min(max(len(a.pool)*2, 1), 64)
	a.pool = make([]JsonValue, newLen)
	a.ofs = 1
	return &a.pool[0]
}
