// Code generated by stefc. DO NOT EDIT.
package profile

import (
	"fmt"
	"math/bits"
	"math/rand/v2"
	"strings"
	"unsafe"

	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/codecs"
	"github.com/splunk/stef/go/pkg/schema"
)

var _ = strings.Compare
var _ = codecs.StringEncoder{}

// LabelValue is a oneof struct.
type LabelValue struct {
	// The current type of the oneof.
	typ LabelValueType
	ptr unsafe.Pointer
	len int

	// Pointer to parent's modifiedFields
	parentModifiedFields *modifiedFields
	// Bit to set in parent's modifiedFields when this oneof is modified.
	parentModifiedBit uint64
}

// Init must be called once, before the LabelValue is used.
func (s *LabelValue) Init() {
	s.init(nil, 0)
}

func (s *LabelValue) init(parentModifiedFields *modifiedFields, parentModifiedBit uint64) {
	s.parentModifiedFields = parentModifiedFields
	s.parentModifiedBit = parentModifiedBit

	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			s.numPtr().init(parentModifiedFields, parentModifiedBit)
		}
	}
}

func (s *LabelValue) initAlloc(parentModifiedFields *modifiedFields, parentModifiedBit uint64, allocators *Allocators) {
	s.parentModifiedFields = parentModifiedFields
	s.parentModifiedBit = parentModifiedBit

	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			s.numPtr().initAlloc(parentModifiedFields, parentModifiedBit, allocators)
		}
	}
}

func (s *LabelValue) clearValue() {
	s.ptr = nil
	s.len = 0
}

func (s *LabelValue) setType(typ LabelValueType) {
	s.clearValue()
	s.typ = typ
	switch typ {
	case LabelValueTypeNum:
		s.allocNum()
	}
}

func (s *LabelValue) setTypeAlloc(typ LabelValueType, allocators *Allocators) {
	s.clearValue()
	s.typ = typ
	switch typ {
	case LabelValueTypeNum:
		allocators.allocSizeChecker.AddAllocSize(uint(unsafe.Sizeof(NumValue{})))
		s.allocNumAlloc(allocators)
	}
}

func (s *LabelValue) decodeSetType(typ LabelValueType, allocators *Allocators) error {
	switch typ {
	case LabelValueTypeNum:
		if err := allocators.allocSizeChecker.PrepAllocSize(uint(unsafe.Sizeof(NumValue{}))); err != nil {
			return err
		}
	}
	s.clearValue()
	s.typ = typ
	switch typ {
	case LabelValueTypeNum:
		s.allocNumAlloc(allocators)
	}
	return nil
}

// reset the struct to its initial state, as if init() was just called.
// Will not reset internal fields such as parentModifiedFields.
func (s *LabelValue) reset() {
	s.typ = LabelValueTypeNone
	s.clearValue()
	// We don't need to reset the state of the field since that will be done
	// when the type is changed, see SetType().
}

func (s *LabelValue) freeze() {
	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			s.numPtr().freeze()
		}
	}
}

// fixParent sets the parentModifiedFields pointer to the supplied value.
// This is used when the parent is moved in memory for example because the parent
// an array element and the array was expanded.
func (s *LabelValue) fixParent(parentModifiedFields *modifiedFields) {
	s.parentModifiedFields = parentModifiedFields

	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			s.numPtr().fixParent(parentModifiedFields)
		}
	}
}

type LabelValueType byte

const (
	LabelValueTypeNone = LabelValueType(iota)
	LabelValueTypeStr
	LabelValueTypeNum
	LabelValueTypeCount
)

// Type returns the type of the value currently contained in LabelValue.
func (s *LabelValue) Type() LabelValueType {
	return s.typ
}

// resetContained resets the currently contained value, if any.
// Normally used after switching to a different type to make sure
// the value contained is in blank state.
func (s *LabelValue) resetContained() {
	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			s.numPtr().reset()
		}
	}
}

// SetType sets the type of the value currently contained in LabelValue.
func (s *LabelValue) SetType(typ LabelValueType) {
	if s.typ != typ {
		s.setType(typ)
		s.markParentModified()
	}
}

func (s *LabelValue) strValue() string {
	if s.len == 0 {
		return string("")
	}
	return string(unsafe.String((*byte)(s.ptr), s.len))
}

func (s *LabelValue) setStrValue(v string) {
	if len(v) == 0 {
		s.ptr = nil
		s.len = 0
		return
	}
	vString := string(v)
	s.ptr = unsafe.Pointer(unsafe.StringData(vString))
	s.len = len(vString)
}

// Str returns the value if the contained type is currently LabelValueTypeStr.
// The caller must check the type via Type() before attempting to call this function.
func (s *LabelValue) Str() string {
	return s.strValue()
}

// SetStr sets the value to the specified value and sets the type to LabelValueTypeStr.
func (s *LabelValue) SetStr(v string) {
	stored := v
	if s.typ != LabelValueTypeStr || s.strValue() != stored {
		if s.typ != LabelValueTypeStr {
			s.clearValue()
			s.typ = LabelValueTypeStr
		}
		s.setStrValue(stored)
		s.parentModifiedFields.markModified(s.parentModifiedBit)
	}
}

func (s *LabelValue) numPtr() *NumValue {
	return (*NumValue)(s.ptr)
}

func (s *LabelValue) allocNum() *NumValue {
	v := &NumValue{}
	v.init(s.parentModifiedFields, s.parentModifiedBit)
	s.ptr = unsafe.Pointer(v)
	return v
}

func (s *LabelValue) allocNumAlloc(allocators *Allocators) *NumValue {
	v := allocators.NumValue.Alloc()
	v.initAlloc(s.parentModifiedFields, s.parentModifiedBit, allocators)
	s.ptr = unsafe.Pointer(v)
	return v
}

// Num returns the value if the contained type is currently LabelValueTypeNum.
// The caller must check the type via Type() before attempting to call this function.
func (s *LabelValue) Num() *NumValue {
	return s.numPtr()
}

func (s *LabelValue) canBeShared() bool {
	// Oneof can never be shared.
	return false
}

func (s *LabelValue) cloneShared(allocators *Allocators) LabelValue {
	// Oneof is not shareable, so cloneShared is just a Clone.
	return s.Clone(allocators)
}

func (s *LabelValue) Clone(allocators *Allocators) LabelValue {
	c := LabelValue{}
	c.clearValue()
	c.typ = s.typ
	switch s.typ {
	case LabelValueTypeStr:
		c.setStrValue(s.strValue())
	case LabelValueTypeNum:
		c.setTypeAlloc(s.typ, allocators)
		copyToNewNumValue(c.numPtr(), s.numPtr(), allocators)
	}
	return c
}

// ByteSize returns approximate memory usage in bytes. Used to calculate
// memory used by dictionaries.
func (s *LabelValue) byteSize() uint {
	size := uint(unsafe.Sizeof(*s))
	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			size += s.numPtr().byteSize()
		}
	}
	return size
}

// Copy from src to dst, overwriting existing data in dst.
func copyLabelValue(dst *LabelValue, src *LabelValue) {
	switch src.typ {
	case LabelValueTypeStr:
		dst.SetStr(src.strValue())
	case LabelValueTypeNum:
		dst.SetType(src.typ)
		copyNumValue(
			dst.numPtr(),
			src.numPtr())
	case LabelValueTypeNone:
		if dst.typ != LabelValueTypeNone {
			dst.clearValue()
			dst.typ = LabelValueTypeNone
			dst.markParentModified()
		}
	default:
		panic("copyLabelValue: unexpected type: " + fmt.Sprint(src.typ))
	}
}

// Copy from src to dst. dst is assumed to be just inited.
func copyToNewLabelValue(dst *LabelValue, src *LabelValue, allocators *Allocators) {
	dst.setTypeAlloc(src.typ, allocators)
	switch src.typ {
	case LabelValueTypeStr:
		if dst.strValue() != src.strValue() {
			dst.setStrValue(src.strValue())
			dst.parentModifiedFields.markModified(dst.parentModifiedBit)
		}
	case LabelValueTypeNum:
		copyToNewNumValue(
			dst.numPtr(),
			src.numPtr(), allocators)
	case LabelValueTypeNone:
	default:
		panic("copyLabelValue: unexpected type: " + fmt.Sprint(src.typ))
	}
}

// CopyFrom() performs a deep copy from src.
func (s *LabelValue) CopyFrom(src *LabelValue) {
	copyLabelValue(s, src)
}

func (s *LabelValue) markParentModified() {
	s.parentModifiedFields.markModified(s.parentModifiedBit)
}

func (s *LabelValue) setModifiedRecursively() {
	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			s.numPtr().setModifiedRecursively()
		}
	}
}

func (s *LabelValue) setUnmodifiedRecursively() {
	switch s.typ {
	case LabelValueTypeNum:
		if s.numPtr() != nil {
			s.numPtr().setUnmodifiedRecursively()
		}
	}
}

// computeDiff compares s and val and returns true if they differ.
// All fields that are different in s will be marked as modified.
func (s *LabelValue) computeDiff(val *LabelValue) (ret bool) {
	if s.typ == val.typ {
		switch s.typ {
		case LabelValueTypeStr:
			ret = s.strValue() != val.strValue()
		case LabelValueTypeNum:
			ret = s.numPtr().computeDiff(val.numPtr())
		}
	} else {
		ret = true
		switch s.typ {
		case LabelValueTypeNum:
			// val.num doesn't exist at all so mark the whole s.num subtree as modified.
			if s.numPtr() != nil {
				s.numPtr().setModifiedRecursively()
			}
		}
	}
	return ret
}

// IsEqual performs deep comparison and returns true if struct is equal to val.
func (e *LabelValue) IsEqual(val *LabelValue) bool {
	if e.typ != val.typ {
		return false
	}
	switch e.typ {
	case LabelValueTypeStr:
		return pkg.StringEqual(e.strValue(), val.strValue())
	case LabelValueTypeNum:
		return e.numPtr().IsEqual(val.numPtr())
	}

	return true
}

// CmpLabelValue performs deep comparison and returns an integer that
// will be 0 if left == right, negative if left < right, positive if left > right.
func CmpLabelValue(left, right *LabelValue) int {
	c := pkg.Uint64Compare(uint64(left.typ), uint64(right.typ))
	if c != 0 {
		return c
	}
	switch left.typ {
	case LabelValueTypeStr:
		return strings.Compare(left.strValue(), right.strValue())
	case LabelValueTypeNum:
		return CmpNumValue(
			left.numPtr(), right.numPtr())
	}

	return 0
}

// mutateRandom mutates fields in a random, deterministic manner using
// random parameter as a deterministic generator. Only fields that exist
// in the schema are mutated, allowing to generate data for specified schema.
func (s *LabelValue) mutateRandom(random *rand.Rand, schem *schema.Schema, limiter *mutateRandomLimiter) {
	// Get the field count for this oneof from the schema. If the schema specifies
	// fewer field count than the one we have in this code then we will not mutate
	// the type of the oneof to the choices that are not in the schema.
	fieldCount, err := schem.FieldCount("LabelValue")
	if err != nil {
		panic(fmt.Sprintf("cannot get field count for %s: %v", "LabelValue", err))
	}

	typeChanged := false
	if random.IntN(10) == 0 {
		s.SetType(LabelValueType(random.IntN(fieldCount + 1)))
		typeChanged = true
	}

	switch s.typ {
	case LabelValueTypeStr:
		if typeChanged || random.IntN(2) == 0 {
			s.SetStr(pkg.StringRandom(random))
		}
	case LabelValueTypeNum:
		if typeChanged || random.IntN(2) == 0 {
			s.numPtr().mutateRandom(random, schem, limiter)
		}
	}
}

// LabelValueEncoder implements encoding of LabelValue
type LabelValueEncoder struct {
	buf     pkg.BitsWriter
	limiter *pkg.SizeLimiter

	// fieldCount is the number of fields, i.e. the number of types in this oneof.
	fieldCount uint
	// Number of bits needed to encode the type (including None type).
	typeBitCount uint

	// Field encoders.
	strEncoder codecs.StringDictEncoder

	numEncoder     *NumValueEncoder
	isNumRecursive bool // Indicates Num field's type is recursive.

}

func (e *LabelValueEncoder) Init(state *WriterState, columns *pkg.WriteColumnSet) error {
	// Remember this encoder in the state so that we can detect recursion.
	if state.LabelValueEncoder != nil {
		panic("cannot initialize LabelValueEncoder: already initialized")
	}
	state.LabelValueEncoder = e
	defer func() { state.LabelValueEncoder = nil }()

	e.limiter = &state.limiter

	var err error
	e.fieldCount, err = state.StructFieldCounts.LabelValueFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %w", "LabelValue", err)
	}
	e.typeBitCount = uint(bits.Len64(uint64(e.fieldCount) + 1))

	// Init encoder for Str field.
	if e.fieldCount <= 0 {
		// Str and all subsequent fields are skipped.
		return nil
	}
	err = e.strEncoder.Init(&state.LabelValue, e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	// Init encoder for Num field.
	if e.fieldCount <= 1 {
		// Num and all subsequent fields are skipped.
		return nil
	}
	if state.NumValueEncoder != nil {
		// Recursion detected, use the existing encoder.
		e.numEncoder = state.NumValueEncoder
		e.isNumRecursive = true
	} else {
		e.numEncoder = new(NumValueEncoder)
		err = e.numEncoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}

	return nil
}

func (e *LabelValueEncoder) Reset() {

	if e.fieldCount <= 0 {
		return // Str and all subsequent fields are skipped.
	}
	e.strEncoder.Reset()
	if e.fieldCount <= 1 {
		return // Num and all subsequent fields are skipped.
	}

	if !e.isNumRecursive {
		e.numEncoder.Reset()
	}

}

// Encode encodes val into buf
func (e *LabelValueEncoder) Encode(val *LabelValue) {
	typ := val.typ
	if uint(typ) > e.fieldCount {
		// The current field type is not supported in target schema. Encode the type as None.
		typ = LabelValueTypeNone
	}

	e.buf.WriteBits(uint64(typ), e.typeBitCount)

	// Account written bits in the limiter.
	e.limiter.AddFrameBits(e.typeBitCount)

	// Encode currently selected field.
	switch typ {
	case LabelValueTypeStr:
		// Encode Str
		e.strEncoder.Encode(val.strValue())
	case LabelValueTypeNum:
		// Encode Num
		e.numEncoder.Encode(val.numPtr())
	}
}

// CollectColumns collects all buffers from all encoders into buf.
func (e *LabelValueEncoder) CollectColumns(columnSet *pkg.WriteColumnSet) {
	columnSet.SetBits(&e.buf)
	colIdx := 0

	// Collect Str field.
	if e.fieldCount <= 0 {
		return // Str and subsequent fields are skipped.
	}

	e.strEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++

	// Collect Num field.
	if e.fieldCount <= 1 {
		return // Num and subsequent fields are skipped.
	}
	if !e.isNumRecursive {
		e.numEncoder.CollectColumns(columnSet.At(colIdx))
		colIdx++
	}
}

// LabelValueDecoder implements decoding of LabelValue
type LabelValueDecoder struct {
	buf        pkg.BitsReader
	column     *pkg.ReadableColumn
	lastValPtr *LabelValue
	lastVal    LabelValue

	// fieldCount is the number of fields, i.e. the number of types in this oneof.
	fieldCount uint
	// Number of bits needed to encode the type (including None type).
	typeBitCount uint

	// Field decoders.

	strDecoder codecs.StringDictDecoder

	numDecoder     *NumValueDecoder
	isNumRecursive bool

	allocators *Allocators
}

// Init is called once in the lifetime of the stream.
func (d *LabelValueDecoder) Init(state *ReaderState, columns *pkg.ReadColumnSet) error {
	// Remember this decoder in the state so that we can detect recursion.
	if state.LabelValueDecoder != nil {
		panic("cannot initialize LabelValueDecoder: already initialized")
	}
	state.LabelValueDecoder = d
	defer func() { state.LabelValueDecoder = nil }()

	d.allocators = &state.Allocators

	var err error
	d.fieldCount, err = state.StructFieldCounts.LabelValueFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %w", "LabelValue", err)
	}
	if d.fieldCount > 2 {
		return pkg.ErrTooManyFieldsToDecode
	}

	d.column = columns.Column()

	d.lastVal.init(nil, 0)
	d.lastValPtr = &d.lastVal

	d.typeBitCount = uint(bits.Len64(uint64(d.fieldCount) + 1))
	if d.fieldCount <= 0 {
		return nil // Str and subsequent fields are skipped.
	}
	err = d.strDecoder.Init(&state.LabelValue, columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 1 {
		return nil // Num and subsequent fields are skipped.
	}
	if state.NumValueDecoder != nil {
		// Recursion detected, use the existing decoder.
		d.numDecoder = state.NumValueDecoder
		d.isNumRecursive = true // Mark that we are using a recursive decoder.
	} else {
		d.numDecoder = new(NumValueDecoder)
		err = d.numDecoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}

	return nil
}

// Continue is called at the start of the frame to continue decoding column data.
// This should set the decoder's source buffer, so the new decoding continues from
// the supplied column data. This should NOT reset the internal state of the decoder,
// since columns can cross frame boundaries and the new column data is considered
// continuation of that same column in the previous frame.
func (d *LabelValueDecoder) Continue() {
	d.buf.Reset(d.column.Data())

	if d.fieldCount <= 0 {
		return // Str and subsequent fields are skipped.
	}
	d.strDecoder.Continue()

	if d.fieldCount <= 1 {
		return // Num and subsequent fields are skipped.
	}

	if !d.isNumRecursive {
		d.numDecoder.Continue()
	}

}

func (d *LabelValueDecoder) Reset() {

	if d.fieldCount <= 0 {
		return // Str and all subsequent fields are skipped.
	}
	d.strDecoder.Reset()
	if d.fieldCount <= 1 {
		return // Num and all subsequent fields are skipped.
	}

	if !d.isNumRecursive {
		d.numDecoder.Reset()
	}

}

func (d *LabelValueDecoder) Decode(dstPtr *LabelValue) error {
	// Read the type and validate it
	typ := uint(d.buf.ReadBits(d.typeBitCount))
	if typ >= uint(d.fieldCount+1) {
		return pkg.ErrInvalidOneOfType
	}
	if err := d.buf.Error(); err != nil {
		return err
	}

	dst := dstPtr
	if dst.typ != LabelValueType(typ) {
		// The type changed, so drop the previous payload and create a blank
		// value for the newly selected type.
		if err := dst.decodeSetType(LabelValueType(typ), d.allocators); err != nil {
			return err
		}
	}

	// Decode selected field
	switch dst.typ {
	case LabelValueTypeStr:
		// Decode Str
		var v string
		if err := d.strDecoder.Decode(&v); err != nil {
			return err
		}
		dst.setStrValue(v)
	case LabelValueTypeNum:
		// Decode Num
		if dst.numPtr() == nil {
			if err := d.allocators.allocSizeChecker.PrepAllocSize(uint(unsafe.Sizeof(NumValue{}))); err != nil {
				return err
			}
			dst.allocNumAlloc(d.allocators)
		}

		return d.numDecoder.Decode(dst.numPtr())
	}
	return nil
}

// LabelValueAllocator implements a custom allocator for LabelValue.
// It maintains a pool of pre-allocated LabelValue and grows the pool
// dynamically as needed, up to a maximum size of 64 elements.
type LabelValueAllocator struct {
	pool []LabelValue
	ofs  int
}

// Alloc returns the next available LabelValue from the pool.
// If the pool is exhausted, it grows the pool by doubling its size
// up to a maximum of 64 elements.
func (a *LabelValueAllocator) Alloc() *LabelValue {
	if a.ofs < len(a.pool) {
		// Get the next available LabelValue from the pool
		a.ofs++
		return &a.pool[a.ofs-1]
	}
	// We've exhausted the current pool, prealloc a new pool.
	return a.prealloc()
}

//go:noinline
func (a *LabelValueAllocator) prealloc() *LabelValue {
	// prealloc expands the pool by doubling its size, up to a maximum of 64 elements.
	// If the pool is empty, it starts with 1 element.
	newLen := min(max(len(a.pool)*2, 1), 64)
	a.pool = make([]LabelValue, newLen)
	a.ofs = 1
	return &a.pool[0]
}
