// Code generated by stefgen. DO NOT EDIT.
package profile

import (
	"bytes"
	"fmt"
	"math/rand/v2"
	"strings"
	"unsafe"

	"modernc.org/b/v2"

	"github.com/splunk/stef/go/pkg"
	"github.com/splunk/stef/go/pkg/encoders"
	"github.com/splunk/stef/go/pkg/schema"
)

var _ = strings.Compare
var _ = encoders.StringEncoder{}
var _ = schema.WireSchema{}
var _ = bytes.NewBuffer

type Location struct {
	mapping  *Mapping
	address  uint64
	lines    LineArray
	isFolded bool

	// modifiedFields keeps track of which fields are modified.
	modifiedFields modifiedFields
	// refNum is non-zero when the struct is stored in a dictionary.
	refNum uint64
}

const LocationStructName = "Location"

// Bitmasks for "modified" flags for each field.
const (
	fieldModifiedLocationMapping = uint64(1 << iota)
	fieldModifiedLocationAddress
	fieldModifiedLocationLines
	fieldModifiedLocationIsFolded
)

// Init must be called once, before the Location is used.
func (s *Location) Init() {
	s.init(nil, 0)
}

func NewLocation() *Location {
	var s Location
	s.init(nil, 0)
	return &s
}

func (s *Location) init(parentModifiedFields *modifiedFields, parentModifiedBit uint64) {
	s.modifiedFields.parent = parentModifiedFields
	s.modifiedFields.parentBit = parentModifiedBit

	s.mapping = &Mapping{}
	s.mapping.init(&s.modifiedFields, fieldModifiedLocationMapping)
	s.lines.init(&s.modifiedFields, fieldModifiedLocationLines)
}

func (s *Location) initAlloc(parentModifiedFields *modifiedFields, parentModifiedBit uint64, allocators *Allocators) {
	s.modifiedFields.parent = parentModifiedFields
	s.modifiedFields.parentBit = parentModifiedBit

	s.mapping = allocators.Mapping.Alloc()
	s.mapping.initAlloc(&s.modifiedFields, fieldModifiedLocationMapping, allocators)
	s.lines.initAlloc(&s.modifiedFields, fieldModifiedLocationLines, allocators)
}

// reset the struct to its initial state, as if init() was just called.
// Will not reset internal fields such as parentModifiedFields.
func (s *Location) reset() {

	if s.mapping != nil {
		s.mapping.reset()
	}
	s.address = 0
	s.lines.reset()
	s.isFolded = false
}

// fixParent sets the parentModifiedFields pointer to the supplied value.
// This is used when the parent is moved in memory for example because the parent
// an array element and the array was expanded.
func (s *Location) fixParent(parentModifiedFields *modifiedFields) {
	s.modifiedFields.parent = parentModifiedFields

	s.mapping.fixParent(&s.modifiedFields)
	s.lines.fixParent(&s.modifiedFields)
}

// Freeze the struct. Any attempt to modify it after this will panic.
// This marks the struct as eligible for safely sharing without cloning
// which can improve performance.
func (s *Location) Freeze() {
	s.modifiedFields.freeze()
}

func (s *Location) Mapping() *Mapping {
	return s.mapping
}

// SetMapping sets the value of Mapping field.
func (s *Location) SetMapping(v *Mapping) {
	if !s.mapping.IsEqual(v) {
		s.mapping = v
		s.markMappingModified()
	}
}

func (s *Location) markMappingModified() {
	s.modifiedFields.markModified(fieldModifiedLocationMapping)
}

// IsMappingModified returns true the value of Mapping field was modified since
// Location was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *Location) IsMappingModified() bool {
	return s.modifiedFields.mask&fieldModifiedLocationMapping != 0
}

func (s *Location) Address() uint64 {
	return s.address
}

// SetAddress sets the value of Address field.
func (s *Location) SetAddress(v uint64) {
	if s.address != v {
		s.address = v
		s.markAddressModified()
	}
}

func (s *Location) markAddressModified() {
	s.modifiedFields.markModified(fieldModifiedLocationAddress)
}

// IsAddressModified returns true the value of Address field was modified since
// Location was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *Location) IsAddressModified() bool {
	return s.modifiedFields.mask&fieldModifiedLocationAddress != 0
}

func (s *Location) Lines() *LineArray {
	return &s.lines
}

func (s *Location) markLinesModified() {
	s.modifiedFields.markModified(fieldModifiedLocationLines)
}

// IsLinesModified returns true the value of Lines field was modified since
// Location was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *Location) IsLinesModified() bool {
	return s.modifiedFields.mask&fieldModifiedLocationLines != 0
}

func (s *Location) IsFolded() bool {
	return s.isFolded
}

// SetIsFolded sets the value of IsFolded field.
func (s *Location) SetIsFolded(v bool) {
	if s.isFolded != v {
		s.isFolded = v
		s.markIsFoldedModified()
	}
}

func (s *Location) markIsFoldedModified() {
	s.modifiedFields.markModified(fieldModifiedLocationIsFolded)
}

// IsIsFoldedModified returns true the value of IsFolded field was modified since
// Location was created, encoded or decoded. If the field is modified
// it will be encoded by the next Write() operation. If the field is decoded by the
// next Read() operation the modified flag will be set.
func (s *Location) IsIsFoldedModified() bool {
	return s.modifiedFields.mask&fieldModifiedLocationIsFolded != 0
}

func (s *Location) markModifiedRecursively() {

	s.mapping.markModifiedRecursively()

	s.lines.markModifiedRecursively()

	s.modifiedFields.mask =
		fieldModifiedLocationMapping |
			fieldModifiedLocationAddress |
			fieldModifiedLocationLines |
			fieldModifiedLocationIsFolded | 0
}

func (s *Location) markUnmodifiedRecursively() {

	if s.IsMappingModified() {
		s.mapping.markUnmodifiedRecursively()
	}

	if s.IsAddressModified() {
	}

	if s.IsLinesModified() {
		s.lines.markUnmodifiedRecursively()
	}

	if s.IsIsFoldedModified() {
	}

	s.modifiedFields.mask = 0
}

func (s *Location) Clone(allocators *Allocators) *Location {

	c := allocators.Location.Alloc()
	*c = Location{

		mapping:  s.mapping.Clone(allocators),
		address:  s.address,
		lines:    s.lines.Clone(allocators),
		isFolded: s.isFolded,
	}
	return c
}

// ByteSize returns approximate memory usage in bytes. Used to calculate
// memory used by dictionaries.
func (s *Location) byteSize() uint {
	return uint(unsafe.Sizeof(*s)) +
		s.mapping.byteSize() + s.lines.byteSize() + 0
}

// Copy from src to dst, overwriting existing data in dst.
func copyLocation(dst *Location, src *Location) {
	if src.mapping != nil {
		if dst.mapping == nil {
			dst.mapping = &Mapping{}
			dst.mapping.init(&dst.modifiedFields, fieldModifiedLocationMapping)
		}
		copyMapping(dst.mapping, src.mapping)
	}
	dst.SetAddress(src.address)
	copyLineArray(&dst.lines, &src.lines)
	dst.SetIsFolded(src.isFolded)
}

// Copy from src to dst. dst is assumed to be just inited.
func copyToNewLocation(dst *Location, src *Location, allocators *Allocators) {
	if src.mapping != nil {
		dst.mapping = allocators.Mapping.Alloc()
		dst.mapping.init(&dst.modifiedFields, fieldModifiedLocationMapping)
		copyToNewMapping(dst.mapping, src.mapping, allocators)
	}
	dst.address = src.address
	copyToNewLineArray(&dst.lines, &src.lines, allocators)
	dst.isFolded = src.isFolded
}

// CopyFrom() performs a deep copy from src.
func (s *Location) CopyFrom(src *Location) {
	copyLocation(s, src)
}

func (s *Location) markParentModified() {
	s.modifiedFields.parent.markModified(s.modifiedFields.parentBit)
}

// mutateRandom mutates fields in a random, deterministic manner using
// random parameter as a deterministic generator. Only fields that exist
// in the schem are mutated, allowing to generate data for specified schema.
func (s *Location) mutateRandom(random *rand.Rand, schem *schema.Schema) {
	// Get the field count for this struct from the schema. If the schema specifies
	// fewer field count than the one we have in this code then we will not mutate
	// fields that are not in the schema.
	fieldCount, err := schem.FieldCount("Location")
	if err != nil {
		panic(fmt.Sprintf("cannot get field count for %s: %v", "Location", err))
	}

	const randRange = max(4, 2) // At least 2 to ensure we don't recurse infinitely if there is only 1 field.

	if fieldCount <= 0 {
		return // Mapping and all subsequent fields are skipped.
	}
	// Maybe mutate Mapping
	if random.IntN(randRange) == 0 {
		s.mapping.mutateRandom(random, schem)
	}
	if fieldCount <= 1 {
		return // Address and all subsequent fields are skipped.
	}
	// Maybe mutate Address
	if random.IntN(randRange) == 0 {
		s.SetAddress(pkg.Uint64Random(random))
	}
	if fieldCount <= 2 {
		return // Lines and all subsequent fields are skipped.
	}
	// Maybe mutate Lines
	if random.IntN(randRange) == 0 {
		s.lines.mutateRandom(random, schem)
	}
	if fieldCount <= 3 {
		return // IsFolded and all subsequent fields are skipped.
	}
	// Maybe mutate IsFolded
	if random.IntN(randRange) == 0 {
		s.SetIsFolded(pkg.BoolRandom(random))
	}
}

// IsEqual performs deep comparison and returns true if struct is equal to right.
func (s *Location) IsEqual(right *Location) bool {
	// Compare Mapping field.
	if !s.mapping.IsEqual(right.mapping) {
		return false
	}
	// Compare Address field.
	if !pkg.Uint64Equal(s.address, right.address) {
		return false
	}
	// Compare Lines field.
	if !s.lines.IsEqual(&right.lines) {
		return false
	}
	// Compare IsFolded field.
	if !pkg.BoolEqual(s.isFolded, right.isFolded) {
		return false
	}

	return true
}

func LocationEqual(left, right *Location) bool {
	return left.IsEqual(right)
}

// CmpLocation performs deep comparison and returns an integer that
// will be 0 if left == right, negative if left < right, positive if left > right.
func CmpLocation(left, right *Location) int {
	if left == nil {
		if right == nil {
			return 0
		}
		return -1
	}
	if right == nil {
		return 1
	}

	// Compare Mapping field.
	if c := CmpMapping(left.mapping, right.mapping); c != 0 {
		return c
	}

	// Compare Address field.
	if c := pkg.Uint64Compare(left.address, right.address); c != 0 {
		return c
	}

	// Compare Lines field.
	if c := CmpLineArray(&left.lines, &right.lines); c != 0 {
		return c
	}

	// Compare IsFolded field.
	if c := pkg.BoolCompare(left.isFolded, right.isFolded); c != 0 {
		return c
	}

	return 0
}

// LocationEncoder implements encoding of Location
type LocationEncoder struct {
	buf     pkg.BitsWriter
	limiter *pkg.SizeLimiter

	// forceModifiedFields is set to true if the next encoding operation
	// must write all fields, whether they are modified or no.
	// This is used after frame restarts so that the data can be decoded
	// from the frame start.
	forceModifiedFields bool

	mappingEncoder     *MappingEncoder
	isMappingRecursive bool // Indicates Mapping field's type is recursive.

	addressEncoder encoders.Uint64Encoder

	linesEncoder     *LineArrayEncoder
	isLinesRecursive bool // Indicates Lines field's type is recursive.

	isFoldedEncoder encoders.BoolEncoder

	dict       *LocationEncoderDict
	allocators *Allocators

	keepFieldMask uint64
	fieldCount    uint
}

type LocationEntry struct {
	refNum uint64
	//val  *Location
}

// LocationEncoderDict is the dictionary used by LocationEncoder
type LocationEncoderDict struct {
	dict b.Tree[*Location, LocationEntry]
	//m       map[*Location]uint64
	limiter *pkg.SizeLimiter
}

func (d *LocationEncoderDict) Init(limiter *pkg.SizeLimiter) {
	d.dict = *b.TreeNew[*Location, LocationEntry](CmpLocation)
	//d.m = make(map[*Location]uint64)
	d.dict.Set(nil, LocationEntry{}) // nil Location is RefNum 0
	d.limiter = limiter
}

func (d *LocationEncoderDict) Get(val *Location) (uint64, bool) {
	if val.refNum != 0 {
		return val.refNum, true
	}
	if entry, ok := d.dict.Get(val); ok {
		return entry.refNum, true
	}
	return 0, false
}

func (d *LocationEncoderDict) Add(val *Location, allocators *Allocators) {
	refNum := uint64(d.dict.Len())
	val.refNum = refNum
	d.dict.Set(val.Clone(allocators), LocationEntry{refNum: refNum})
}

func (d *LocationEncoderDict) Reset() {
	d.dict.Clear()
	d.dict.Set(nil, LocationEntry{}) // nil Location is RefNum 0
}

func (e *LocationEncoder) Init(state *WriterState, columns *pkg.WriteColumnSet) error {
	// Remember this encoder in the state so that we can detect recursion.
	if state.LocationEncoder != nil {
		panic("cannot initialize LocationEncoder: already initialized")
	}
	state.LocationEncoder = e
	defer func() { state.LocationEncoder = nil }()

	e.limiter = &state.limiter
	e.dict = &state.Location
	e.allocators = &state.Allocators

	// Number of fields in the output data schema.
	var err error
	e.fieldCount, err = state.StructFieldCounts.LocationFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %v", "Location", err)
	}
	// Set that many 1 bits in the keepFieldMask. All fields with higher number
	// will be skipped when encoding.
	e.keepFieldMask = ^(^uint64(0) << e.fieldCount)

	// Init encoder for Mapping field.
	if e.fieldCount <= 0 {
		return nil // Mapping and all subsequent fields are skipped.
	}
	if state.MappingEncoder != nil {
		// Recursion detected, use the existing encoder.
		e.mappingEncoder = state.MappingEncoder
		e.isMappingRecursive = true
	} else {
		e.mappingEncoder = new(MappingEncoder)
		err = e.mappingEncoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}

	// Init encoder for Address field.
	if e.fieldCount <= 1 {
		return nil // Address and all subsequent fields are skipped.
	}
	err = e.addressEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	// Init encoder for Lines field.
	if e.fieldCount <= 2 {
		return nil // Lines and all subsequent fields are skipped.
	}
	if state.LineArrayEncoder != nil {
		// Recursion detected, use the existing encoder.
		e.linesEncoder = state.LineArrayEncoder
		e.isLinesRecursive = true
	} else {
		e.linesEncoder = new(LineArrayEncoder)
		err = e.linesEncoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}

	// Init encoder for IsFolded field.
	if e.fieldCount <= 3 {
		return nil // IsFolded and all subsequent fields are skipped.
	}
	err = e.isFoldedEncoder.Init(e.limiter, columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

func (e *LocationEncoder) Reset() {
	// Since we are resetting the state of encoder make sure the next Encode()
	// call forcedly writes all fields and does not attempt to skip.
	e.forceModifiedFields = true

	if e.fieldCount <= 0 {
		return // Mapping and all subsequent fields are skipped.
	}

	if !e.isMappingRecursive {
		e.mappingEncoder.Reset()
	}

	if e.fieldCount <= 1 {
		return // Address and all subsequent fields are skipped.
	}
	e.addressEncoder.Reset()
	if e.fieldCount <= 2 {
		return // Lines and all subsequent fields are skipped.
	}

	if !e.isLinesRecursive {
		e.linesEncoder.Reset()
	}

	if e.fieldCount <= 3 {
		return // IsFolded and all subsequent fields are skipped.
	}
	e.isFoldedEncoder.Reset()
}

// Encode encodes val into buf
func (e *LocationEncoder) Encode(val *Location) {
	var bitCount uint

	// Check if the Location exists in the dictionary.
	//refNum := val.refNum
	if refNum, exists := e.dict.Get(val); exists {
		// The Location exists, we will reference it.
		// Indicate a RefNum follows.
		e.buf.WriteBit(0)
		// Encode refNum.
		bitCount = e.buf.WriteUvarintCompact(refNum)

		// Account written bits in the limiter.
		e.limiter.AddFrameBits(1 + bitCount)

		// Mark all fields non-modified recursively so that next Encode() correctly
		// encodes only fields that change after this.
		val.markUnmodifiedRecursively()
		return
	}

	// The Location does not exist in the dictionary. Add it to the dictionary.
	e.dict.Add(val, e.allocators)
	//valInDict := val // val.Clone(e.allocators)
	//val.refNum = uint64(len(e.dict.m)+1)
	//entry := LocationEntry{refNum: uint64(len(e.dict.m)+1), val: valInDict}
	//e.dict.dict.Set(valInDict, entry)
	//e.dict.m[val] = val.refNum
	e.dict.limiter.AddDictElemSize(val.byteSize())

	// Indicate that an encoded Location follows.
	e.buf.WriteBit(1)
	bitCount += 1
	// TODO: optimize and merge WriteBit with the following WriteBits.
	// Mask that describes what fields are encoded. Start with all modified fields.
	fieldMask := val.modifiedFields.mask

	// If forceModifiedFields we need to set to 1 all bits so that we
	// force writing of all fields.
	if e.forceModifiedFields {
		fieldMask =
			fieldModifiedLocationMapping |
				fieldModifiedLocationAddress |
				fieldModifiedLocationLines |
				fieldModifiedLocationIsFolded | 0
	}

	// Only write fields that we want to write. See Init() for keepFieldMask.
	fieldMask &= e.keepFieldMask

	// Write bits to indicate which fields follow.
	e.buf.WriteBits(fieldMask, e.fieldCount)
	bitCount += e.fieldCount

	// Encode modified, present fields.

	if fieldMask&fieldModifiedLocationMapping != 0 {
		// Encode Mapping
		e.mappingEncoder.Encode(val.mapping)
	}

	if fieldMask&fieldModifiedLocationAddress != 0 {
		// Encode Address
		e.addressEncoder.Encode(val.address)
	}

	if fieldMask&fieldModifiedLocationLines != 0 {
		// Encode Lines
		e.linesEncoder.Encode(&val.lines)
	}

	if fieldMask&fieldModifiedLocationIsFolded != 0 {
		// Encode IsFolded
		e.isFoldedEncoder.Encode(val.isFolded)
	}

	// Account written bits in the limiter.
	e.limiter.AddFrameBits(bitCount)

	// Mark all fields non-modified so that next Encode() correctly
	// encodes only fields that change after this.
	val.modifiedFields.mask = 0
}

// CollectColumns collects all buffers from all encoders into buf.
func (e *LocationEncoder) CollectColumns(columnSet *pkg.WriteColumnSet) {
	columnSet.SetBits(&e.buf)
	colIdx := 0

	// Collect Mapping field.
	if e.fieldCount <= 0 {
		return // Mapping and subsequent fields are skipped.
	}
	if !e.isMappingRecursive {
		e.mappingEncoder.CollectColumns(columnSet.At(colIdx))
		colIdx++
	}

	// Collect Address field.
	if e.fieldCount <= 1 {
		return // Address and subsequent fields are skipped.
	}

	e.addressEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++

	// Collect Lines field.
	if e.fieldCount <= 2 {
		return // Lines and subsequent fields are skipped.
	}
	if !e.isLinesRecursive {
		e.linesEncoder.CollectColumns(columnSet.At(colIdx))
		colIdx++
	}

	// Collect IsFolded field.
	if e.fieldCount <= 3 {
		return // IsFolded and subsequent fields are skipped.
	}

	e.isFoldedEncoder.CollectColumns(columnSet.At(colIdx))
	colIdx++
}

// LocationDecoder implements decoding of Location
type LocationDecoder struct {
	buf        pkg.BitsReader
	column     *pkg.ReadableColumn
	fieldCount uint

	mappingDecoder     *MappingDecoder
	isMappingRecursive bool

	addressDecoder encoders.Uint64Decoder

	linesDecoder     *LineArrayDecoder
	isLinesRecursive bool

	isFoldedDecoder encoders.BoolDecoder

	dict *LocationDecoderDict

	allocators *Allocators
}

// Init is called once in the lifetime of the stream.
func (d *LocationDecoder) Init(state *ReaderState, columns *pkg.ReadColumnSet) error {
	// Remember this decoder in the state so that we can detect recursion.
	if state.LocationDecoder != nil {
		panic("cannot initialize LocationDecoder: already initialized")
	}
	state.LocationDecoder = d
	defer func() { state.LocationDecoder = nil }()

	d.allocators = &state.Allocators

	// Number of fields in the input data schema.
	var err error
	d.fieldCount, err = state.StructFieldCounts.LocationFieldCount()
	if err != nil {
		return fmt.Errorf("cannot find struct %s in override schema: %v", "Location", err)
	}

	d.column = columns.Column()
	d.dict = &state.Location

	if d.fieldCount <= 0 {
		return nil // Mapping and subsequent fields are skipped.
	}
	if state.MappingDecoder != nil {
		// Recursion detected, use the existing decoder.
		d.mappingDecoder = state.MappingDecoder
		d.isMappingRecursive = true // Mark that we are using a recursive decoder.
	} else {
		d.mappingDecoder = new(MappingDecoder)
		err = d.mappingDecoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}
	if d.fieldCount <= 1 {
		return nil // Address and subsequent fields are skipped.
	}
	err = d.addressDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}
	if d.fieldCount <= 2 {
		return nil // Lines and subsequent fields are skipped.
	}
	if state.LineArrayDecoder != nil {
		// Recursion detected, use the existing decoder.
		d.linesDecoder = state.LineArrayDecoder
		d.isLinesRecursive = true // Mark that we are using a recursive decoder.
	} else {
		d.linesDecoder = new(LineArrayDecoder)
		err = d.linesDecoder.Init(state, columns.AddSubColumn())
	}
	if err != nil {
		return err
	}
	if d.fieldCount <= 3 {
		return nil // IsFolded and subsequent fields are skipped.
	}
	err = d.isFoldedDecoder.Init(columns.AddSubColumn())
	if err != nil {
		return err
	}

	return nil
}

// Continue is called at the start of the frame to continue decoding column data.
// This should set the decoder's source buffer, so the new decoding continues from
// the supplied column data. This should NOT reset the internal state of the decoder,
// since columns can cross frame boundaries and the new column data is considered
// continuation of that same column in the previous frame.
func (d *LocationDecoder) Continue() {
	d.buf.Reset(d.column.Data())

	if d.fieldCount <= 0 {
		return // Mapping and subsequent fields are skipped.
	}

	if !d.isMappingRecursive {
		d.mappingDecoder.Continue()
	}

	if d.fieldCount <= 1 {
		return // Address and subsequent fields are skipped.
	}
	d.addressDecoder.Continue()
	if d.fieldCount <= 2 {
		return // Lines and subsequent fields are skipped.
	}

	if !d.isLinesRecursive {
		d.linesDecoder.Continue()
	}

	if d.fieldCount <= 3 {
		return // IsFolded and subsequent fields are skipped.
	}
	d.isFoldedDecoder.Continue()
}

func (d *LocationDecoder) Reset() {

	if d.fieldCount <= 0 {
		return // Mapping and all subsequent fields are skipped.
	}

	if !d.isMappingRecursive {
		d.mappingDecoder.Reset()
	}

	if d.fieldCount <= 1 {
		return // Address and all subsequent fields are skipped.
	}
	d.addressDecoder.Reset()
	if d.fieldCount <= 2 {
		return // Lines and all subsequent fields are skipped.
	}

	if !d.isLinesRecursive {
		d.linesDecoder.Reset()
	}

	if d.fieldCount <= 3 {
		return // IsFolded and all subsequent fields are skipped.
	}
	d.isFoldedDecoder.Reset()
}

func (d *LocationDecoder) Decode(dstPtr **Location) error {
	// Check if this is a dictionary-based decoding.
	dictFlag := d.buf.ReadBit()
	if dictFlag == 0 {
		refNum := d.buf.ReadUvarintCompact()
		if refNum >= uint64(len(d.dict.dict)) {
			return pkg.ErrInvalidRefNum
		}
		*dstPtr = d.dict.dict[refNum]
		return nil
	}

	// *dstPtr is pointing to a element in the dictionary. We are not allowed
	// to modify it. Make a clone of it and decode into the clone.
	val := (*dstPtr).Clone(d.allocators)
	*dstPtr = val

	var err error

	// Read bits that indicate which fields follow.
	val.modifiedFields.mask = d.buf.ReadBits(d.fieldCount)

	if val.modifiedFields.mask&fieldModifiedLocationMapping != 0 {
		// Field is changed and is present, decode it.
		if val.mapping == nil {
			val.mapping = d.allocators.Mapping.Alloc()
			val.mapping.init(&val.modifiedFields, fieldModifiedLocationMapping)
		}

		err = d.mappingDecoder.Decode(&val.mapping)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedLocationAddress != 0 {
		// Field is changed and is present, decode it.
		err = d.addressDecoder.Decode(&val.address)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedLocationLines != 0 {
		// Field is changed and is present, decode it.
		err = d.linesDecoder.Decode(&val.lines)
		if err != nil {
			return err
		}
	}

	if val.modifiedFields.mask&fieldModifiedLocationIsFolded != 0 {
		// Field is changed and is present, decode it.
		err = d.isFoldedDecoder.Decode(&val.isFolded)
		if err != nil {
			return err
		}
	}

	d.dict.dict = append(d.dict.dict, val)
	// Freeze the value. It is now in the dictionary and must not be modified.
	// This also improves performance of any encode operations that use this
	// value as it can be safely shared in encoder's dictionary without cloning.
	val.Freeze()

	return nil
}

// LocationDecoderDict is the dictionary used by LocationDecoder
type LocationDecoderDict struct {
	dict []*Location
}

func (d *LocationDecoderDict) Init() {
	d.dict = d.dict[:0]
	d.dict = append(d.dict, nil) // nil Location is RefNum 0
}

// Reset the dictionary to initial state. Used when a frame is
// started with RestartDictionaries flag.
func (d *LocationDecoderDict) Reset() {
	d.Init()
}

// LocationAllocator implements a custom allocator for Location.
// It maintains a pool of pre-allocated Location and grows the pool
// dynamically as needed, up to a maximum size of 64 elements.
type LocationAllocator struct {
	pool []Location
	ofs  int
}

// Alloc returns the next available Location from the pool.
// If the pool is exhausted, it grows the pool by doubling its size
// up to a maximum of 64 elements.
func (a *LocationAllocator) Alloc() *Location {
	if a.ofs < len(a.pool) {
		// Get the next available Location from the pool
		a.ofs++
		return &a.pool[a.ofs-1]
	}
	// We've exhausted the current pool, prealloc a new pool.
	return a.prealloc()
}

//go:noinline
func (a *LocationAllocator) prealloc() *Location {
	// prealloc expands the pool by doubling its size, up to a maximum of 64 elements.
	// If the pool is empty, it starts with 1 element.
	newLen := min(max(len(a.pool)*2, 1), 64)
	a.pool = make([]Location, newLen)
	a.ofs = 1
	return &a.pool[0]
}
