// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.5
// source: jsonl.proto

package jsonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *JsonValue `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jsonl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_jsonl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_jsonl_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetValue() *JsonValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type JsonValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*JsonValue_Object
	//	*JsonValue_Array
	//	*JsonValue_String_
	//	*JsonValue_Number
	//	*JsonValue_Bool
	Kind isJsonValue_Kind `protobuf_oneof:"kind"`
}

func (x *JsonValue) Reset() {
	*x = JsonValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jsonl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonValue) ProtoMessage() {}

func (x *JsonValue) ProtoReflect() protoreflect.Message {
	mi := &file_jsonl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonValue.ProtoReflect.Descriptor instead.
func (*JsonValue) Descriptor() ([]byte, []int) {
	return file_jsonl_proto_rawDescGZIP(), []int{1}
}

func (m *JsonValue) GetKind() isJsonValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *JsonValue) GetObject() *JsonObject {
	if x, ok := x.GetKind().(*JsonValue_Object); ok {
		return x.Object
	}
	return nil
}

func (x *JsonValue) GetArray() *JsonArray {
	if x, ok := x.GetKind().(*JsonValue_Array); ok {
		return x.Array
	}
	return nil
}

func (x *JsonValue) GetString_() string {
	if x, ok := x.GetKind().(*JsonValue_String_); ok {
		return x.String_
	}
	return ""
}

func (x *JsonValue) GetNumber() float64 {
	if x, ok := x.GetKind().(*JsonValue_Number); ok {
		return x.Number
	}
	return 0
}

func (x *JsonValue) GetBool() bool {
	if x, ok := x.GetKind().(*JsonValue_Bool); ok {
		return x.Bool
	}
	return false
}

type isJsonValue_Kind interface {
	isJsonValue_Kind()
}

type JsonValue_Object struct {
	Object *JsonObject `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type JsonValue_Array struct {
	Array *JsonArray `protobuf:"bytes,2,opt,name=array,proto3,oneof"`
}

type JsonValue_String_ struct {
	String_ string `protobuf:"bytes,3,opt,name=string,proto3,oneof"`
}

type JsonValue_Number struct {
	Number float64 `protobuf:"fixed64,4,opt,name=number,proto3,oneof"`
}

type JsonValue_Bool struct {
	Bool bool `protobuf:"varint,5,opt,name=bool,proto3,oneof"`
}

func (*JsonValue_Object) isJsonValue_Kind() {}

func (*JsonValue_Array) isJsonValue_Kind() {}

func (*JsonValue_String_) isJsonValue_Kind() {}

func (*JsonValue_Number) isJsonValue_Kind() {}

func (*JsonValue_Bool) isJsonValue_Kind() {}

type JsonObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elems []*JsonObjectElem `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
}

func (x *JsonObject) Reset() {
	*x = JsonObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jsonl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonObject) ProtoMessage() {}

func (x *JsonObject) ProtoReflect() protoreflect.Message {
	mi := &file_jsonl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonObject.ProtoReflect.Descriptor instead.
func (*JsonObject) Descriptor() ([]byte, []int) {
	return file_jsonl_proto_rawDescGZIP(), []int{2}
}

func (x *JsonObject) GetElems() []*JsonObjectElem {
	if x != nil {
		return x.Elems
	}
	return nil
}

type JsonObjectElem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *JsonValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *JsonObjectElem) Reset() {
	*x = JsonObjectElem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jsonl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonObjectElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonObjectElem) ProtoMessage() {}

func (x *JsonObjectElem) ProtoReflect() protoreflect.Message {
	mi := &file_jsonl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonObjectElem.ProtoReflect.Descriptor instead.
func (*JsonObjectElem) Descriptor() ([]byte, []int) {
	return file_jsonl_proto_rawDescGZIP(), []int{3}
}

func (x *JsonObjectElem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *JsonObjectElem) GetValue() *JsonValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// Array of JsonValue
type JsonArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*JsonValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *JsonArray) Reset() {
	*x = JsonArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jsonl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonArray) ProtoMessage() {}

func (x *JsonArray) ProtoReflect() protoreflect.Message {
	mi := &file_jsonl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonArray.ProtoReflect.Descriptor instead.
func (*JsonArray) Descriptor() ([]byte, []int) {
	return file_jsonl_proto_rawDescGZIP(), []int{4}
}

func (x *JsonArray) GetValues() []*JsonValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_jsonl_proto protoreflect.FileDescriptor

var file_jsonl_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6a, 0x73, 0x6f, 0x6e, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6a,
	0x73, 0x6f, 0x6e, 0x70, 0x62, 0x22, 0x31, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x09, 0x4a, 0x73, 0x6f,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e,
	0x4a, 0x73, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4a, 0x73, 0x6f,
	0x6e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x22, 0x3a, 0x0a, 0x0a, 0x4a, 0x73, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x2c, 0x0a, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x52, 0x05, 0x65, 0x6c, 0x65, 0x6d, 0x73, 0x22, 0x4b, 0x0a,
	0x0e, 0x4a, 0x73, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36, 0x0a, 0x09, 0x4a, 0x73,
	0x6f, 0x6e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62,
	0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x70, 0x6c, 0x75, 0x6e, 0x6b, 0x2f, 0x73, 0x74, 0x65, 0x66, 0x2f, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jsonl_proto_rawDescOnce sync.Once
	file_jsonl_proto_rawDescData = file_jsonl_proto_rawDesc
)

func file_jsonl_proto_rawDescGZIP() []byte {
	file_jsonl_proto_rawDescOnce.Do(func() {
		file_jsonl_proto_rawDescData = protoimpl.X.CompressGZIP(file_jsonl_proto_rawDescData)
	})
	return file_jsonl_proto_rawDescData
}

var file_jsonl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jsonl_proto_goTypes = []interface{}{
	(*Record)(nil),         // 0: jsonpb.Record
	(*JsonValue)(nil),      // 1: jsonpb.JsonValue
	(*JsonObject)(nil),     // 2: jsonpb.JsonObject
	(*JsonObjectElem)(nil), // 3: jsonpb.JsonObjectElem
	(*JsonArray)(nil),      // 4: jsonpb.JsonArray
}
var file_jsonl_proto_depIdxs = []int32{
	1, // 0: jsonpb.Record.value:type_name -> jsonpb.JsonValue
	2, // 1: jsonpb.JsonValue.object:type_name -> jsonpb.JsonObject
	4, // 2: jsonpb.JsonValue.array:type_name -> jsonpb.JsonArray
	3, // 3: jsonpb.JsonObject.elems:type_name -> jsonpb.JsonObjectElem
	1, // 4: jsonpb.JsonObjectElem.value:type_name -> jsonpb.JsonValue
	1, // 5: jsonpb.JsonArray.values:type_name -> jsonpb.JsonValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_jsonl_proto_init() }
func file_jsonl_proto_init() {
	if File_jsonl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jsonl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jsonl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jsonl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jsonl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonObjectElem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jsonl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_jsonl_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*JsonValue_Object)(nil),
		(*JsonValue_Array)(nil),
		(*JsonValue_String_)(nil),
		(*JsonValue_Number)(nil),
		(*JsonValue_Bool)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jsonl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jsonl_proto_goTypes,
		DependencyIndexes: file_jsonl_proto_depIdxs,
		MessageInfos:      file_jsonl_proto_msgTypes,
	}.Build()
	File_jsonl_proto = out.File
	file_jsonl_proto_rawDesc = nil
	file_jsonl_proto_goTypes = nil
	file_jsonl_proto_depIdxs = nil
}
